// Listes d'armee + aliases extraits de TOW en 1.
const AUGUR_AL = {
  "empire-of-man":{
    characters:[
      {n:"General of the Empire",s:"general-of-the-empire"},
      {n:"Grand Master",s:"grand-master"},
      {n:"Lector of Sigmar (0-1)",s:"lector-of-sigmar"},
      {n:"High Priest of Ulric (0-1)",s:"high-priest-of-ulric"},
      {n:"Captain of the Empire",s:"captain-of-the-empire"},
      {n:"Wizard Lord",s:"wizard-lord"},
      {n:"Master Mage",s:"master-mage"},
      {n:"Chapter Master",s:"chapter-master"},
      {n:"Witch Hunter",s:"witch-hunter"},
      {n:"Priest of Sigmar",s:"priest-of-sigmar"},
      {n:"Priest of Ulric",s:"priest-of-ulric"},
      {n:"Empire Engineer",s:"empire-engineer"},
      {n:"War Altar of Sigmar (0-1)",s:"war-altar-of-sigmar"},
      {n:"Harbinger of Doom",s:"harbinger-of-doom"},
    ],
    core:[
      {n:"State Troops",s:"state-troops"},
      {n:"State Missile Troops",s:"state-missile-troops"},
      {n:"Free Company Militia",s:"free-company-militia"},
      {n:"Empire Archers",s:"empire-archers"},
      {n:"Empire Knights",s:"empire-knights"},
      {n:"Veteran State Troops (0-1)",s:"veteran-state-troops"},
    ],
    special:[
      {n:"Empire Greatswords",s:"empire-greatswords"},
      {n:"Pistoliers",s:"pistoliers"},
      {n:"Outriders",s:"outriders"},
      {n:"Demigryph Knights",s:"demigryph-knights"},
      {n:"Inner Circle Knights (0-1)",s:"inner-circle-knights"},
      {n:"Teutogen Guard (cond.)",s:"teutogen-guard"},
      {n:"Empire Road Wardens (0-1)",s:"empire-road-wardens"},
      {n:"Great Cannon",s:"great-cannon"},
      {n:"Mortar",s:"mortar"},
    ],
    rare:[
      {n:"Flagellants",s:"flagellants"},
      {n:"Helblaster Volley Gun (0-1)",s:"helblaster-volley-gun"},
      {n:"Helstorm Rocket Battery (0-1)",s:"helstorm-rocket-battery"},
      {n:"Empire Steam Tank (0-1)",s:"empire-steam-tank"},
      {n:"Empire War Wagon (0-1)",s:"empire-war-wagon"},
    ],
    mercenaries:[
      {n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"},
      {n:"Prince Ulther's Dragon Company",s:"prince-ulthers-dragon-company"},
      {n:"Doomseekers (0-3)",s:"doomseeker"},
      {n:"Imperial Dwarf Mercenaries (0-1)",s:"imperial-dwarf-mercenaries"},
      {n:"Imperial Ogres (0-1)",s:"imperial-ogres"},
    ],
    allies:["Dwarfen Mountain Holds","Grand Cathay","Kingdom of Bretonnia","Wood Elf Realms (Suspicious)"],
  },
  "beastmen-brayherds":{
    characters:[
      {n:"Doombull",s:"doombull"},{n:"Great Bray-Shaman",s:"great-bray-shaman"},
      {n:"Bray-Shaman",s:"bray-shaman"},{n:"Wargor",s:"wargor"},{n:"Gorebull",s:"gorebull"},
    ],
    core:[
      {n:"Gor Herd",s:"gor-herd"},{n:"Ungor Herd",s:"ungor-herd"},
      {n:"Ungor Raiders",s:"ungor-raiders"},{n:"Tuskgor Chariots",s:"tuskgor-chariots"},
    ],
    special:[
      {n:"Bestigors",s:"bestigors"},{n:"Minotaurs",s:"minotaurs"},
      {n:"Chaos Ogres",s:"chaos-ogres"},{n:"Harpies",s:"harpies"},
      {n:"Razorgor Herd",s:"razorgor-herd"},{n:"Razorgor Chariot",s:"razorgor-chariot"},
      {n:"Warhounds of Chaos",s:"warhounds-of-chaos"},
    ],
    rare:[
      {n:"Chaos Trolls",s:"chaos-trolls"},{n:"Cygor",s:"cygor"},
      {n:"Ghorgon",s:"ghorgon"},{n:"Dragon Ogres",s:"dragon-ogres"},
    ],
    mercenaries:[
      {n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"},
      {n:"Chaos Marauder Horsemen (cond.)",s:"chaos-marauder-horsemen"},
    ],
    allies:["Warriors of Chaos","Daemons of Chaos (Suspicious)"],
  },
  "dwarfen-mountain-holds":{
    characters:[
      {n:"Dwarf King",s:"dwarf-king"},{n:"Dwarf Thane",s:"dwarf-thane"},
      {n:"Dwarf Runesmith",s:"dwarf-runesmith"},{n:"Dwarf Runelord",s:"dwarf-runelord"},
      {n:"Dwarf Master Engineer",s:"dwarf-master-engineer"},
      {n:"Dwarf Dragon Slayer",s:"dwarf-dragon-slayer"},
      {n:"Dwarf Daemon Slayer",s:"dwarf-daemon-slayer"},
    ],
    core:[
      {n:"Dwarf Warriors",s:"dwarf-warriors"},{n:"Dwarf Longbeards",s:"dwarf-longbeards"},
      {n:"Dwarf Quarrellers",s:"dwarf-quarrellers"},{n:"Dwarf Thunderers",s:"dwarf-thunderers"},
      {n:"Dwarf Rangers",s:"dwarf-rangers"},
    ],
    special:[
      {n:"Dwarf Ironbreakers",s:"dwarf-ironbreakers"},{n:"Dwarf Hammerers",s:"dwarf-hammerers"},
      {n:"Dwarf Slayers",s:"dwarf-slayers"},{n:"Dwarf Miners",s:"dwarf-miners"},
      {n:"Gyrobombers (0-1)",s:"gyrobombers"},{n:"Gyrocopters",s:"gyrocopters"},
      {n:"Dwarf Bolt Thrower",s:"dwarf-bolt-thrower"},
      {n:"Dwarf Cannon",s:"dwarf-cannon"},{n:"Dwarf Organ Gun (0-1)",s:"dwarf-organ-gun"},
    ],
    rare:[
      {n:"Dwarf Irondrakes",s:"dwarf-irondrakes"},
      {n:"Dwarf Flame Cannon",s:"dwarf-flame-cannon"},
      {n:"Dwarf Grudge Thrower",s:"dwarf-grudge-thrower"},
    ],
    mercenaries:[
      {n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"},
      {n:"Doomseekers",s:"doomseeker"},
    ],
    allies:["Empire of Man","Grand Cathay"],
  },
  "grand-cathay":{
    characters:[
      {n:"Dragon Blooded Shugengan Lord",s:"dragon-blooded-shugengan-lord"},
      {n:"Celestial Dragon Emperor (0-1)",s:"celestial-dragon-emperor"},
      {n:"Cathayan Dragon (0-1)",s:"cathayan-dragon"},
      {n:"Jade Warrior Captain",s:"jade-warrior-captain"},
      {n:"Wu Xing War Compass (0-1)",s:"wu-xing-war-compass"},
      {n:"Astromancer Lord",s:"astromancer-lord"},
      {n:"Astromancer",s:"astromancer"},
      {n:"Monkey King (0-1)",s:"monkey-king"},
    ],
    core:[
      {n:"Jade Warriors",s:"jade-warriors"},{n:"Peasant Archers",s:"peasant-archers"},
      {n:"Cathayan Cavalry",s:"cathayan-cavalry"},
      {n:"Terracotta Sentinel",s:"terracotta-sentinel"},
    ],
    special:[
      {n:"Jade Lancers",s:"jade-lancers"},{n:"Dragon Guard",s:"dragon-guard"},
      {n:"Sky Lantern (0-1)",s:"sky-lantern"},
      {n:"Cathayan Celestial Dragon (0-1)",s:"cathayan-celestial-dragon"},
      {n:"Grand Cannon",s:"grand-cannon"},
      {n:"Iron Hail Gunners",s:"iron-hail-gunners"},
      {n:"Crane Gunners",s:"crane-gunners"},
    ],
    rare:[
      {n:"Storm-Dragon Ogres (cond.)",s:"storm-dragon-ogres"},
      {n:"Flying Boat (0-1)",s:"flying-boat"},
      {n:"Fire Rain Rocket",s:"fire-rain-rocket"},
    ],
    mercenaries:[{n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"}],
    allies:["Empire of Man","Dwarfen Mountain Holds","High Elf Realms"],
  },
  "high-elf-realms":{
    characters:[
      {n:"Prince",s:"prince"},{n:"Princess",s:"princess"},
      {n:"Loremaster (0-1)",s:"loremaster"},{n:"Noble",s:"noble"},
      {n:"Archmage",s:"archmage"},{n:"Mage",s:"mage"},
      {n:"Caradryan (0-1)",s:"caradryan"},
      {n:"Tyrion (0-1)",s:"tyrion"},{n:"Teclis (0-1)",s:"teclis"},
      {n:"Korhil (0-1)",s:"korhil"},
    ],
    core:[
      {n:"Lothern Sea Guard",s:"lothern-sea-guard"},{n:"Spearmen",s:"spearmen"},
      {n:"Archers",s:"archers"},{n:"Ellyrian Reavers",s:"ellyrian-reavers"},
      {n:"Silver Helms",s:"silver-helms"},
    ],
    special:[
      {n:"Sword Masters of Hoeth",s:"sword-masters-of-hoeth"},
      {n:"Shadow Warriors",s:"shadow-warriors"},
      {n:"White Lions of Chrace",s:"white-lions-of-chrace"},
      {n:"Dragon Princes of Caledor",s:"dragon-princes-of-caledor"},
      {n:"Phoenix Guard",s:"phoenix-guard"},
      {n:"Bolt Thrower",s:"bolt-thrower"},
      {n:"Lion Chariots of Chrace",s:"lion-chariots-of-chrace"},
      {n:"Tiranoc Chariots",s:"tiranoc-chariots"},
    ],
    rare:[
      {n:"Lothern Skycutters",s:"lothern-skycutters"},
      {n:"Sisters of Avelorn",s:"sisters-of-avelorn"},
      {n:"Frostheart Phoenix (0-1)",s:"frostheart-phoenix"},
      {n:"Flamespyre Phoenix (0-1)",s:"flamespyre-phoenix"},
      {n:"Great Eagle",s:"great-eagle"},
      {n:"Eagle Claw Bolt Thrower",s:"eagle-claw-bolt-thrower"},
    ],
    mercenaries:[{n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"}],
    allies:["Grand Cathay","Wood Elf Realms","Kingdom of Bretonnia (Suspicious)"],
  },
  "kingdom-of-bretonnia":{
    characters:[
      {n:"Bretonnian Lord",s:"bretonnian-lord"},{n:"Paladin",s:"paladin"},
      {n:"Prophetess (0-1)",s:"prophetess"},{n:"Damsel",s:"damsel"},
      {n:"The Green Knight (0-1)",s:"the-green-knight"},
    ],
    core:[
      {n:"Knights of the Realm",s:"knights-of-the-realm"},
      {n:"Peasant Bowmen",s:"peasant-bowmen"},
      {n:"Men-at-Arms",s:"men-at-arms"},
    ],
    special:[
      {n:"Questing Knights",s:"questing-knights"},
      {n:"Pegasus Knights",s:"pegasus-knights"},
      {n:"Trebuchet",s:"trebuchet"},
      {n:"Mounted Yeomen",s:"mounted-yeomen"},
      {n:"Field Trebuchet",s:"field-trebuchet"},
    ],
    rare:[
      {n:"Grail Knights",s:"grail-knights"},
      {n:"Grail Reliquae",s:"grail-reliquae"},
    ],
    mercenaries:[
      {n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"},
      {n:"Imperial Dwarf Mercenaries (0-1)",s:"imperial-dwarf-mercenaries"},
    ],
    allies:["Empire of Man","High Elf Realms (Suspicious)"],
  },
  "orc-and-goblin-tribes":{
    characters:[
      {n:"Orc Warboss",s:"orc-warboss"},{n:"Black Orc Warboss",s:"black-orc-warboss"},
      {n:"Orc Big Boss",s:"orc-big-boss"},{n:"Black Orc Big Boss",s:"black-orc-big-boss"},
      {n:"Orc Shaman",s:"orc-shaman"},{n:"Night Goblin Shaman",s:"night-goblin-shaman"},
      {n:"Goblin Warboss",s:"goblin-warboss"},{n:"Goblin Big Boss",s:"goblin-big-boss"},
      {n:"Goblin Shaman",s:"goblin-shaman"},
      {n:"Savage Orc Warboss",s:"savage-orc-warboss"},
      {n:"Savage Orc Big Boss",s:"savage-orc-big-boss"},
    ],
    core:[
      {n:"Orc Boyz",s:"orc-boyz"},{n:"Orc Big Uns",s:"orc-big-uns"},
      {n:"Orc Arrer Boyz",s:"orc-arrer-boyz"},
      {n:"Savage Orcs",s:"savage-orcs"},{n:"Night Goblins",s:"night-goblins"},
      {n:"Goblins",s:"goblins"},{n:"Forest Goblins",s:"forest-goblins"},
      {n:"Wolf Riders",s:"wolf-riders"},{n:"Spider Riders",s:"spider-riders"},
      {n:"Orc Boar Boyz",s:"orc-boar-boyz"},{n:"Orc Boar Chariots",s:"orc-boar-chariots"},
    ],
    special:[
      {n:"Black Orcs",s:"black-orcs"},
      {n:"Night Goblin Fanatics (cond.)",s:"night-goblin-fanatics"},
      {n:"Squig Herd",s:"squig-herd"},{n:"Squig Hoppers",s:"squig-hoppers"},
      {n:"Goblin Wolf Chariots",s:"goblin-wolf-chariots"},
      {n:"Savage Orc Boar Boyz",s:"savage-orc-boar-boyz"},
      {n:"Doom Diver Catapult",s:"doom-diver-catapult"},
      {n:"Rock Lobber",s:"rock-lobber"},
      {n:"Snotlings",s:"snotlings"},{n:"Giant",s:"giant"},
      {n:"Troll Herd",s:"troll-herd"},
    ],
    rare:[
      {n:"Arachnarok Spider",s:"arachnarok-spider"},
      {n:"Mangler Squigs",s:"mangler-squigs"},
      {n:"Pump Wagon (cond.)",s:"pump-wagon"},
      {n:"Nasty Skulkers (cond.)",s:"nasty-skulkers"},
    ],
    mercenaries:[{n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"}],
    allies:["Ogre Kingdoms"],
  },
  "tomb-kings-of-khemri":{
    characters:[
      {n:"Tomb King",s:"tomb-king"},
      {n:"Tomb King on Bone Dragon",s:"tomb-king-on-necrolith-bone-dragon"},
      {n:"Liche Priest",s:"liche-priest"},{n:"Tomb Herald",s:"tomb-herald"},
      {n:"Settra the Imperishable (0-1)",s:"settra-the-imperishable"},
    ],
    core:[
      {n:"Skeleton Warriors",s:"skeleton-warriors"},
      {n:"Skeleton Archers",s:"skeleton-archers"},
      {n:"Skeleton Horsemen",s:"skeleton-horsemen"},
      {n:"Skeleton Horse Archers",s:"skeleton-horse-archers"},
    ],
    special:[
      {n:"Tomb Guard",s:"tomb-guard"},{n:"Ushabti",s:"ushabti"},
      {n:"Necropolis Knights",s:"necropolis-knights"},
      {n:"Skeleton Chariots",s:"skeleton-chariots"},
      {n:"Screaming Skull Catapult",s:"screaming-skull-catapult"},
      {n:"Casket of Souls (0-1)",s:"casket-of-souls"},
    ],
    rare:[
      {n:"Bone Giant",s:"bone-giant"},{n:"Hierotitan",s:"hierotitan"},
      {n:"Necrosphinx",s:"necrosphinx"},{n:"Khemrian Warsphinx",s:"khemrian-warsphinx"},
      {n:"Carrion",s:"carrion"},
    ],
    mercenaries:[],
    allies:[],
  },
  "warriors-of-chaos":{
    characters:[
      {n:"Chaos Lord",s:"chaos-lord"},{n:"Exalted Hero",s:"exalted-hero"},
      {n:"Sorcerer Lord",s:"sorcerer-lord"},{n:"Sorcerer",s:"sorcerer"},
      {n:"Daemon Prince (0-1)",s:"daemon-prince"},
      {n:"Chaos Lord on Manticore",s:"chaos-lord-on-manticore"},
    ],
    core:[
      {n:"Chaos Warriors",s:"chaos-warriors"},
      {n:"Chaos Marauders",s:"chaos-marauders"},
      {n:"Chaos Marauder Horsemen",s:"chaos-marauder-horsemen"},
      {n:"Chaos Knights",s:"chaos-knights"},
      {n:"Chaos Warhounds",s:"chaos-warhounds"},
    ],
    special:[
      {n:"Chaos Chosen",s:"chaos-chosen"},{n:"Chaos Trolls",s:"chaos-trolls"},
      {n:"Chaos Ogres",s:"chaos-ogres"},{n:"Dragon Ogres",s:"dragon-ogres"},
      {n:"Chaos Chariot",s:"chaos-chariot"},{n:"Gorebeast Chariot",s:"gorebeast-chariot"},
      {n:"Hellcannon",s:"hellcannon"},
    ],
    rare:[
      {n:"Dragon Ogre Shaggoth",s:"dragon-ogre-shaggoth"},
      {n:"Chaos War Mammoth (0-1)",s:"chaos-war-mammoth"},
      {n:"Skullcrushers of Khorne",s:"skullcrushers-of-khorne"},
    ],
    mercenaries:[
      {n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"},
    ],
    allies:["Beastmen Brayherds","Daemons of Chaos (Suspicious)"],
  },
  "wood-elf-realms":{
    characters:[
      {n:"Glade Lord",s:"glade-lord"},{n:"Glade Captain",s:"glade-captain"},
      {n:"Spellweaver",s:"spellweaver"},{n:"Spellsinger",s:"spellsinger"},
      {n:"Shadowdancer",s:"shadowdancer"},{n:"Waystalker",s:"waystalker"},
      {n:"Orion King of the Hunt (0-1)",s:"orion-king-of-the-hunt"},
      {n:"Drycha (0-1)",s:"drycha"},
    ],
    core:[
      {n:"Glade Guard",s:"glade-guard"},{n:"Dryads",s:"dryads"},
      {n:"Glade Riders",s:"glade-riders"},
    ],
    special:[
      {n:"Wardancers",s:"wardancers"},{n:"Waywatchers",s:"waywatchers"},
      {n:"Wildwood Rangers",s:"wildwood-rangers"},
      {n:"Tree Kin",s:"tree-kin"},{n:"Wild Riders",s:"wild-riders"},
      {n:"Deepwood Scouts",s:"deepwood-scouts"},
      {n:"Warhawk Riders",s:"warhawk-riders"},
      {n:"Great Eagle",s:"great-eagle"},
    ],
    rare:[
      {n:"Treeman Ancient",s:"treeman-ancient"},
      {n:"Treeman",s:"treeman"},{n:"Eternal Guard",s:"eternal-guard"},
    ],
    mercenaries:[],
    allies:["High Elf Realms","Empire of Man (Suspicious)"],
  },
  "chaos-dwarfs":{
    legacy:true,
    characters:[
      {n:"Chaos Dwarf Sorcerer-Prophet",s:"chaos-dwarf-sorcerer-prophet"},
      {n:"Chaos Dwarf Daemonsmith",s:"chaos-dwarf-daemonsmith"},
      {n:"Chaos Dwarf Castellan",s:"chaos-dwarf-castellan"},
      {n:"Infernal Castellan",s:"infernal-castellan"},
    ],
    core:[
      {n:"Chaos Dwarf Warriors",s:"chaos-dwarf-warriors"},
      {n:"Chaos Dwarf Blunderbusses",s:"chaos-dwarf-blunderbusses"},
      {n:"Hobgoblin Cutthroats",s:"hobgoblin-cutthroats"},
    ],
    special:[
      {n:"Infernal Guard",s:"infernal-guard"},
      {n:"Hobgoblin Wolf Raiders",s:"hobgoblin-wolf-raiders"},
      {n:"Bull Centaurs",s:"bull-centaurs"},
      {n:"Hobgoblin Bolt Thrower",s:"hobgoblin-bolt-thrower"},
      {n:"Death Rocket",s:"death-rocket"},
    ],
    rare:[
      {n:"K'daai Fireborn",s:"kdaai-fireborn"},
      {n:"Iron Daemon War Engine",s:"iron-daemon-war-engine"},
      {n:"Magma Cannon",s:"magma-cannon"},
      {n:"Dreadquake Mortar",s:"dreadquake-mortar"},
    ],
    mercenaries:[{n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"}],
    allies:[],
  },
  "daemons-of-chaos":{
    legacy:true,
    characters:[
      {n:"Bloodthirster (0-1)",s:"bloodthirster"},
      {n:"Lord of Change (0-1)",s:"lord-of-change"},
      {n:"Great Unclean One (0-1)",s:"great-unclean-one"},
      {n:"Keeper of Secrets (0-1)",s:"keeper-of-secrets"},
      {n:"Daemon Prince",s:"daemon-prince"},
      {n:"Herald of Khorne",s:"herald-of-khorne"},
      {n:"Herald of Tzeentch",s:"herald-of-tzeentch"},
      {n:"Herald of Nurgle",s:"herald-of-nurgle"},
      {n:"Herald of Slaanesh",s:"herald-of-slaanesh"},
    ],
    core:[
      {n:"Bloodletters of Khorne",s:"bloodletters-of-khorne"},
      {n:"Horrors of Tzeentch",s:"horrors-of-tzeentch"},
      {n:"Plaguebearers of Nurgle",s:"plaguebearers-of-nurgle"},
      {n:"Daemonettes of Slaanesh",s:"daemonettes-of-slaanesh"},
    ],
    special:[
      {n:"Flesh Hounds of Khorne",s:"flesh-hounds-of-khorne"},
      {n:"Flamers of Tzeentch",s:"flamers-of-tzeentch"},
      {n:"Beasts of Nurgle",s:"beasts-of-nurgle"},
      {n:"Fiends of Slaanesh",s:"fiends-of-slaanesh"},
      {n:"Chaos Furies",s:"chaos-furies"},
      {n:"Seekers of Slaanesh",s:"seekers-of-slaanesh"},
      {n:"Screamers of Tzeentch",s:"screamers-of-tzeentch"},
    ],
    rare:[
      {n:"Skull Cannon of Khorne",s:"skull-cannon-of-khorne"},
      {n:"Soul Grinder",s:"soul-grinder"},
      {n:"Exalted Flamers of Tzeentch",s:"exalted-flamers-of-tzeentch"},
    ],
    mercenaries:[],
    allies:["Warriors of Chaos (Suspicious)","Beastmen Brayherds (Suspicious)"],
  },
  "dark-elves":{
    legacy:true,
    characters:[
      {n:"Dreadlord",s:"dreadlord"},{n:"Malekith (0-1)",s:"malekith"},
      {n:"Supreme Sorceress",s:"supreme-sorceress"},{n:"Sorceress",s:"sorceress"},
      {n:"Death Hag",s:"death-hag"},{n:"Master",s:"master"},
    ],
    core:[
      {n:"Dark Elf Warriors",s:"dark-elf-warriors"},
      {n:"Dark Elf Crossbowmen",s:"dark-elf-crossbowmen"},
      {n:"Dark Riders",s:"dark-riders"},{n:"Corsairs",s:"corsairs"},
    ],
    special:[
      {n:"Black Guard of Naggarond",s:"black-guard-of-naggarond"},
      {n:"Cold One Knights",s:"cold-one-knights"},
      {n:"Witch Elves",s:"witch-elves"},
      {n:"Executioners",s:"executioners"},
      {n:"Cold One Chariot",s:"cold-one-chariot"},
      {n:"Reaper Bolt Thrower",s:"reaper-bolt-thrower"},
    ],
    rare:[
      {n:"War Hydra",s:"war-hydra"},
      {n:"Bloodwrack Shrine",s:"bloodwrack-shrine"},
      {n:"Shades",s:"shades"},
    ],
    mercenaries:[{n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"}],
    allies:[],
  },
  "lizardmen":{
    legacy:true,
    characters:[
      {n:"Slann Mage-Priest",s:"slann-mage-priest"},
      {n:"Saurus Oldblood",s:"saurus-oldblood"},
      {n:"Skink Chief",s:"skink-chief"},
      {n:"Saurus Scar-Veteran",s:"saurus-scar-veteran"},
      {n:"Skink Priest",s:"skink-priest"},
    ],
    core:[
      {n:"Saurus Warriors",s:"saurus-warriors"},
      {n:"Skinks",s:"skinks"},{n:"Skink Cohort",s:"skink-cohort"},
    ],
    special:[
      {n:"Temple Guard",s:"temple-guard"},
      {n:"Saurus Cavalry",s:"saurus-cavalry"},
      {n:"Kroxigors",s:"kroxigors"},
      {n:"Chameleon Skinks",s:"chameleon-skinks"},
      {n:"Terradons",s:"terradons"},
      {n:"Salamander Hunting Pack",s:"salamander-hunting-pack"},
      {n:"Razordon Hunting Pack",s:"razordon-hunting-pack"},
      {n:"Stegadon",s:"stegadon"},
    ],
    rare:[
      {n:"Ancient Stegadon",s:"ancient-stegadon"},
      {n:"Bastiladon",s:"bastiladon"},{n:"Troglodon",s:"troglodon"},
    ],
    mercenaries:[],allies:[],
  },
  "ogre-kingdoms":{
    legacy:true,
    characters:[
      {n:"Tyrant",s:"tyrant"},{n:"Bruiser",s:"bruiser"},
      {n:"Butcher",s:"butcher"},{n:"Slaughtermaster",s:"slaughtermaster"},
      {n:"Firebelly",s:"firebelly"},
    ],
    core:[
      {n:"Ogre Bulls",s:"ogre-bulls"},{n:"Ironguts",s:"ironguts"},
      {n:"Gnoblars",s:"gnoblars"},
    ],
    special:[
      {n:"Leadbelchers",s:"leadbelchers"},{n:"Mournfang Cavalry",s:"mournfang-cavalry"},
      {n:"Yhettis (cond.)",s:"yhettis"},
      {n:"Ironblaster",s:"ironblaster"},{n:"Scraplauncher",s:"scraplauncher"},
    ],
    rare:[
      {n:"Stonehorn",s:"stonehorn"},{n:"Thundertusk",s:"thundertusk"},
      {n:"Gorgers",s:"gorgers"},{n:"Maneaters",s:"maneaters"},
    ],
    mercenaries:[],allies:["Orc & Goblin Tribes"],
  },
  "skaven":{
    legacy:true,
    characters:[
      {n:"Grey Seer",s:"grey-seer"},{n:"Vermin Lord",s:"vermin-lord"},
      {n:"Warlord",s:"warlord"},{n:"Chieftain",s:"chieftain"},
      {n:"Master Moulder",s:"master-moulder"},{n:"Warlock Engineer",s:"warlock-engineer"},
      {n:"Plague Priest",s:"plague-priest"},
    ],
    core:[
      {n:"Skaven Clanrats",s:"skaven-clanrats"},
      {n:"Skaven Stormvermin",s:"skaven-stormvermin"},
      {n:"Skaven Slaves",s:"skaven-slaves"},
      {n:"Giant Rats",s:"giant-rats"},
    ],
    special:[
      {n:"Plague Monks",s:"plague-monks"},
      {n:"Night Runners",s:"night-runners"},
      {n:"Gutter Runners",s:"gutter-runners"},
      {n:"Rat Ogres",s:"rat-ogres"},
      {n:"Poisoned Wind Mortars",s:"poisoned-wind-mortars"},
      {n:"Warplock Jezzails",s:"warplock-jezzails"},
      {n:"Plague Censor Bearers",s:"plague-censor-bearers"},
      {n:"Warp-Grinder Weapon Team",s:"warp-grinder-weapon-team"},
    ],
    rare:[
      {n:"Plague Furnace (0-1)",s:"plague-furnace"},
      {n:"Screaming Bell (0-1)",s:"screaming-bell"},
      {n:"Doomwheel",s:"doomwheel"},
      {n:"Warp Lightning Cannon",s:"warp-lightning-cannon"},
      {n:"Hell Pit Abomination (0-1)",s:"hell-pit-abomination"},
    ],
    mercenaries:[],allies:[],
  },
  "vampire-counts":{
    legacy:true,
    characters:[
      {n:"Vampire Lord",s:"vampire-lord"},
      {n:"Strigoi Ghoul King",s:"strigoi-ghoul-king"},
      {n:"Necromancer",s:"necromancer"},
      {n:"Vampire",s:"vampire"},{n:"Wight King",s:"wight-king"},
    ],
    core:[
      {n:"Skeleton Warriors",s:"skeleton-warriors-vc"},
      {n:"Zombies",s:"zombies"},{n:"Crypt Ghouls",s:"crypt-ghouls"},
      {n:"Dire Wolves",s:"dire-wolves"},{n:"Bats",s:"bats"},
    ],
    special:[
      {n:"Grave Guard",s:"grave-guard"},{n:"Black Knights",s:"black-knights"},
      {n:"Hexwraiths",s:"hexwraiths"},{n:"Spirit Hosts",s:"spirit-hosts"},
      {n:"Cairn Wraiths",s:"cairn-wraiths"},
      {n:"Vargheists",s:"vargheists"},{n:"Corpse Cart",s:"corpse-cart"},
    ],
    rare:[
      {n:"Blood Knights",s:"blood-knights"},
      {n:"Terrorgheist (0-1)",s:"terrorgheist"},
      {n:"Varghulf",s:"varghulf"},
      {n:"Black Coach (0-1)",s:"black-coach"},
      {n:"Mortis Engine (0-1)",s:"mortis-engine"},
    ],
    mercenaries:[],allies:[],
  },
  "realms-of-men":{
    special_army:true,
    characters:[
      {n:"Renegade Prince (0-1)",s:"renegade-prince"},
      {n:"Renegade Captain",s:"renegade-captain"},
      {n:"Outcast Wizard",s:"outcast-wizard"},
    ],
    core:[
      {n:"Veteran Sellswords (0-1)",s:"veteran-sellswords"},
      {n:"Sellsword Infantry",s:"sellsword-infantry"},
      {n:"Freeblade Knights",s:"freeblade-knights"},
      {n:"Hireling Outriders",s:"hireling-outriders"},
      {n:"Free Company Militia",s:"free-company-militia"},
      {n:"Empire Archers",s:"empire-archers"},
    ],
    special:[
      {n:"Veteran Freeblades",s:"veteran-freeblades"},
      {n:"Border Princes Mortar (0-2)",s:"border-princes-mortar"},
    ],
    rare:[
      {n:"Border Princes Brigands",s:"border-princes-brigands"},
      {n:"Border Princes Organ Gun (0-1)",s:"border-princes-organ-gun"},
      {n:"Border Princes Bombard",s:"border-princes-bombard"},
    ],
    mercenaries:[
      {n:"Badlands Ogre Bulls",s:"badlands-ogre-bulls"},
      {n:"Doomseekers",s:"doomseeker"},
      {n:"Imperial Dwarf Mercenaries",s:"imperial-dwarf-mercenaries"},
      {n:"Imperial Ogres",s:"imperial-ogres"},
    ],
    allies:[],
  },
  "regiments-of-renown":{
    special_army:true,
    characters:[],
    core:[
      {n:"Prince Ulther's Dragon Company",s:"prince-ulthers-dragon-company"},
      {n:"Bugman's Rangers",s:"bugmans-rangers"},
      {n:"Doomseekers",s:"doomseeker"},
    ],
    special:[
      {n:"Golgfag's Mercenary Ogres",s:"golgfags-mercenary-ogres"},
    ],
    rare:[],mercenaries:[],allies:[],
  },
};
const AUGUR_ALIASES = {
  'badlands-ogre-bulls':'badland-ogre-bulls',
  'bloodwrack-shrine':'bloodwrack-shrines',
  'empire-war-wagon':'war-wagon',
  'frostheart-phoenix':'frostheart-phoenix-',
  'helstorm-rocket-battery':'helstrom-rocket-battery',
  'kdaai-fireborn':"k'daai-fireborn",
  'prince-ulthers-dragon-company':"prince-ulther's-dragon-company",
  'razorgor-chariot':'razergor-chariot',
  'razorgor-herd':'razorgor-herds',
  'reaper-bolt-thrower':'reaper-bolt-throwers',
  'sisters-of-avelorn':'sister-of-avelorn',
  'skeleton-warriors-vc':'skeleton-warriors',
  'sword-masters-of-hoeth':'swordmasters',
  'tree-kin':'treekin',
  'tuskgor-chariots':'tuskgor-chariots-',
  'white-lions-of-chrace':'white-lions',
  'gor-herd':'gor-herds',
  'chaos-warhounds':'warhounds',
  'tomb-guard':'tomb-guard-core',
  'deepwood-scouts':'deepwood-scouts-core',
  'seekers-of-slaanesh':'seekers-of-slaanesh-core',
  'cold-one-chariot':'cold-one-chariots',
  'saurus-warriors':'saurus-warrior',
  'settra-the-imperishable':'settra-the-imperishable-the-great-king-of-nehekhara',
  'supreme-astromancer':'astromancer-lord',
  'crane-gunner-teams':'crane-gunners',
  'archers':'elven-archers',
  'dragon-princes-of-caledor':'dragon-princes',
  'korhil':'korhil-lionmane',
  'lion-chariots-of-chrace':'lion-chariot-of-chrace',
  'lothern-skycutters':'lothern-skycutter',
  'spearmen':'elven-spearmen',
  'sword-masters-of-hoeth':'swordmasters-of-hoeth',
  'tiranoc-chariots':'tiranoc-chariot',
  'cathayan-cavalry':'jade-lancers',
  'dragon-blooded-shugengan-lord':'shugengan-lord',
  'fire-rain-rocket':'fire-rain-rocket-battery',
  'grand-cannon':'cathayan-grand-cannon',
  'jade-warrior-captain':'lord-magistrate',
  'terracotta-sentinel':'cathayan-sentinel',
  'bestigors':'bestigor-herd',
  'minotaurs':'minotaur-herd',
  'tuskgor-chariots':'tuskgor-chariot',
  'ungor-raiders':'ungor-ravagers',
  'warhounds-of-chaos':'chaos-warhounds',
  'bull-centaurs':'bull-centaur-renders',
  'chaos-dwarf-blunderbusses':'infernal-guard',
  'chaos-dwarf-castellan':'infernal-castellan',
  'chaos-dwarf-daemonsmith':'daemonsmith-sorcerer',
  'chaos-dwarf-sorcerer-prophet':'sorcerer-prophet',
  'chaos-dwarf-warriors':'infernal-ironsworn',
  'death-rocket':'deathshrieker-rocket-launcher',
  'hobgoblin-wolf-raiders':'hobgoblin-wolf-riders',
  'iron-daemon-war-engine':'iron-daemon',
  'daemon-prince':'daemon-prince-daemons-of-chaos',
  'exalted-flamers-of-tzeentch':'flamers-of-tzeentch',
  'herald-of-khorne':'daemonic-herald-of-khorne',
  'herald-of-nurgle':'daemonic-herald-of-nurgle',
  'herald-of-slaanesh':'daemonic-herald-of-slaanesh',
  'herald-of-tzeentch':'daemonic-herald-of-tzeentch',
  'horrors-of-tzeentch':'pink-horrors-of-tzeentch',
  'corsairs':'black-ark-corsairs',
  'dark-elf-crossbowmen':'repeater-crossbowmen',
  'dreadlord':'dark-elf-dreadlord',
  'executioners':'har-ganeth-executioners',
  'master':'dark-elf-master',
  'shades':'dark-elf-shades',
  'dwarf-bolt-thrower':'bolt-thrower',
  'dwarf-cannon':'cannon',
  'dwarf-daemon-slayer':'daemon-slayer',
  'dwarf-dragon-slayer':'dragon-slayer',
  'dwarf-flame-cannon':'flame-cannon',
  'dwarf-grudge-thrower':'grudge-thrower',
  'dwarf-hammerers':'hammerers',
  'dwarf-ironbreakers':'ironbreakers',
  'dwarf-irondrakes':'irondrakes',
  'dwarf-king':'king',
  'dwarf-longbeards':'longbeards',
  'dwarf-master-engineer':'engineer',
  'dwarf-miners':'miners',
  'dwarf-organ-gun':'organ-gun',
  'dwarf-quarrellers':'quarrellers',
  'dwarf-rangers':'rangers',
  'dwarf-runelord':'runelord',
  'dwarf-runesmith':'runesmith',
  'dwarf-slayers':'slayers',
  'dwarf-thane':'thane',
  'dwarf-thunderers':'thunderers',
  'gyrobombers':'gyrobomber',
  'gyrocopters':'gyrocopter',
  'bretonnian-lord':'duke',
  'grail-reliquae':'battle-pilgrims',
  'knights-of-the-realm':'mounted-knights-of-the-realm',
  'trebuchet':'field-trebuchet',
  'kroxigors':'kroxigor',
  'razordon-hunting-pack':'razordon-pack',
  'salamander-hunting-pack':'salamander-pack',
  'saurus-cavalry':'cold-one-riders',
  'skink-cohort':'skink-skirmishers',
  'skinks':'skink-skirmishers',
  'terradons':'terradon',
  'gnoblars':'gnoblar-fighters',
  'gorgers':'gorger',
  'scraplauncher':'gnoblar-scraplauncher',
  'yhettis':'yhetees',
  'black-orc-big-boss':'black-orc-bigboss',
  'black-orcs':'black-orc-mob',
  'forest-goblins':'goblin-mob',
  'goblin-big-boss':'goblin-bigboss',
  'goblin-shaman':'goblin-oddgit',
  'goblin-wolf-chariots':'goblin-wolf-chariot',
  'goblins':'goblin-mob',
  'nasty-skulkers':'nasty-skulker',
  'night-goblin-fanatics':'fanatic',
  'night-goblin-shaman':'night-goblin-oddgit',
  'night-goblins':'night-goblin-mob',
  'orc-arrer-boyz':'orc-mob',
  'orc-big-boss':'orc-bigboss',
  'orc-big-uns':'orc-mob',
  'orc-boar-boyz':'orc-boar-boy-mob',
  'orc-boar-chariots':'orc-boar-chariot',
  'orc-boyz':'orc-mob',
  'orc-shaman':'orc-weirdboy',
  'pump-wagon':'snotling-pump-wagon',
  'rock-lobber':'goblin-rock-lobber',
  'snotlings':'snotling-mob',
  'spider-riders':'goblin-spider-rider-mob',
  'squig-herd':'night-goblin-squig-herd',
  'squig-hoppers':'night-goblin-squig-hopper-mob',
  'troll-herd':'common-troll-mob',
  'wolf-riders':'goblin-wolf-rider-mob',
  'chieftain':'skaven-chieftain',
  'plague-censor-bearers':'plague-censer-bearers',
  'poisoned-wind-mortars':'poisoned-wind-globadiers',
  'skaven-clanrats':'clanrats',
  'skaven-stormvermin':'stormvermin',
  'warlord':'skaven-warlord',
  'warp-grinder-weapon-team':'weapon-team',
  'bone-giant':'necrolith-colossus',
  'liche-priest':'mortuary-priest',
  'skeleton-warriors':'skeleton-warriors-tomb-kings',
  'tomb-herald':'royal-herald',
  'bats':'bat-swarms',
  'cairn-wraiths':'cairn-wraith',
  'necromancer':'master-necromancer',
  'skeleton-warriors-vc':'skeleton-warriors-vampire-counts',
  'vampire':'vampire-count',
  'chaos-chosen':'chosen-chaos-warriors',
  'chaos-lord-on-manticore':'chaos-lord',
  'chaos-marauder-horsemen':'marauder-horsemen',
  'exalted-hero':'exalted-champion',
  'sorcerer':'sorcerer-lord',
  'orion-king-of-the-hunt':'orion-the-king-in-the-woods',
  'goblin-wolf-chariot':'wolf-chariot',
  'orc-boar-chariot':'boar-chariot',
  'longma':'great-spirit-longma',
  'chariot-of-the-gods':'the-chariot-of-the-gods',
  'treeman-ancient':'treemen-ancient',
  'sang-froid':'cold-one',
  'coursier-squelette':'skeletal-steed',
  'griffon-empire':'griffon',
  'griffon-high-elves':'griffon',
  'manticore-dark-elves':'manticore',
  'manticore-renegade':'manticore',
  'manticore-warriors-of-chaos':'manticore',
  'skeletal-steed-tomb-kings':'skeletal-steed',
  'skeletal-steed-vampire-counts':'skeletal-steed',

};
const augurResolveSlug = s => (AUGUR_ALIASES[s] || s);
