window.MAGIC_ITEMS_DB = {
  weapon: {
    "common": [
      {n:"Ogre Blade", pts:75, d:"S+2, AP-2. A broad and heavy blade."},
      {n:"Cackling Blade", pts:65, d:"S+1, AP-1. If a natural 6 is rolled for Extra Attacks (+D6), the wielder loses 1 Wound."},
      {n:"Sword of Battle", pts:60, d:"S+1, AP-1. +1 Attack."},
      {n:"Duellist's Blades", pts:55, d:"S, AP-1. +2 Attacks. Must be used as an additional hand weapon."},
      {n:"Dragon Slaying Sword", pts:50, d:"S, -. The wielder has the Armour Bane (D3) and Heroic Killing Blow special rules against models with the Large Target special rule."},
      {n:"Meteor Hammer", pts:50, d:"S, AP-3. Roll To Wound on 3+ always succeeds regardless of Toughness."},
      {n:"Headsman's Axe", pts:45, d:"S+1, AP-1. The wielder has the Killing Blow and Heroic Killing Blow special rules."},
      {n:"Spelleater Axe", pts:35, d:"S, AP-1. The wielder dispels one spell per Magic phase as a bound spell (Power Level 2). No roll required."},
      {n:"Giant Blade", pts:30, d:"S+1, -. The wielder has the Strike First special rule."},
      {n:"Hell-forged Axe", pts:30, d:"S+1, AP-1. Flaming Attacks."},
      {n:"Sword of Sorrow", pts:30, d:"30\", S5, AP-1. Missile weapon only; no Ward or Regeneration saves permitted."},
      {n:"Sword of Swiftness", pts:25, d:"S, -. The wielder has +2 Attacks."},
      {n:"Berserker Blade", pts:20, d:"S+1, -. Wielder gains Impetuous."},
      {n:"Sword of Might", pts:20, d:"S+1, AP-1. Extremely Common."},
      {n:"Biting Blade", pts:15, d:"S, AP-2."},
      {n:"Sword of Striking", pts:15, d:"S, -. +1 To Hit modifier in Combat. Extremely Common."},
      {n:"Burning Blade", pts:5, d:"S, -. Flaming Attacks. Extremely Common."},
    ],
    "beastmen-brayherds": [
      {n:"The Black Maul", pts:80, d:"S+2, AP-3. Each nat 6 for Extra Attacks (+D6) gives -1 WS to the wielder (permanent, min 1)."},
      {n:"Primeval Club", pts:60, d:"Str=current Leadership, AP-3. A club of ancient and terrible power."},
      {n:"Axe of Men", pts:50, d:"S, AP-1. Killing an enemy character in a challenge grants the Terror special rule for the rest of the game."},
      {n:"The Axes of Khorgor", pts:40, d:"S+1, AP-2. Re-roll rolls To Wound of a natural 1 in Combat."},
      {n:"Mangelder", pts:40, d:"S+1, AP-1. Causes Terror. Enemy unit hit suffers -1 Ld (min 2) until end of turn."},
      {n:"Hunter's Spear", pts:35, d:"24\", S6, AP-3. Shoots like a bolt thrower using Through & Through."},
      {n:"The Brass Cleaver", pts:30, d:"S, AP-2. Natural 6 To Wound: no armour, Ward or Regen save permitted."},
      {n:"Scimitar of Skultar", pts:25, d:"S, AP-1."},
    ],
    "chaos-dwarfs": [
      {n:"Black Hammer of Hashut", pts:60, d:"S+2, AP-1. Against Flammable models, also has Killing Blow."},
      {n:"Dark Maul", pts:50, d:"S, AP-2. On hit: enemy makes Str test or loses 1 additional Wound."},
      {n:"Dagger of Malice", pts:35, d:"S, -. The wielder cannot lose Frenzy."},
      {n:"The Graven Sceptre", pts:30, d:"S+1, -. Roll To Wound on 4+ always succeeds."},
    ],
    "warriors-of-chaos": [
      {n:"Daemonsword", pts:75, d:"S+D3, AP-2. Natural 1 To Hit = hit on own unit (or wielder if alone)."},
      {n:"Obsidian Dread-Glaive", pts:55, d:"S+2, AP-1. Heralds of Darkness only."},
      {n:"Chaos Runesword", pts:45, d:"S+1, AP-1. +1 WS and +1 Initiative to wielder."},
      {n:"Filth Mace", pts:40, d:"S+1, AP-1. On hit: enemy makes Toughness test or -1 Toughness until end of turn."},
      {n:"Dagger of the Dark Pantheon", pts:35, d:"S, AP-2. Each Wound caused grants +1 to next Casting or Dispel roll."},
      {n:"Chieftain's Blade", pts:30, d:"S+1, AP-1. Wolves of the Sea only. +1 To Hit in challenges."},
      {n:"Taskmaster's Scourge", pts:25, d:"S, AP-1. Infantry only. Pass Ld test: +D3 Movement to unit until next turn."},
      {n:"Spellthieving Sword", pts:20, d:"S, AP-1. Enemy Wizard hit: must forget a random spell."},
    ],
    "empire-of-man": [
      {n:"Runefang", pts:100, d:"S, AP-2. Roll To Wound on 2+ always succeeds."},
      {n:"Mace of Helsturm", pts:65, d:"Single-handed: S, -. Double-handed: S10, AP-5, 1 attack only. Choose at start of each combat round."},
      {n:"Hammer of Righteousness", pts:50, d:"S+2, AP-2. Each hit: enemy makes Ld test or auto-wounds with no armour save."},
      {n:"Sword of Justice", pts:50, d:"S, AP-1. Re-roll failed rolls To Wound."},
      {n:"Pearl Daggers", pts:35, d:"S, AP-1. Re-roll failed rolls To Hit in Combat."},
      {n:"Blade of Silvered Steel", pts:30, d:"S+1, AP-1. Knightly Order only. Undead cannot make Armour or Regen saves vs this weapon."},
      {n:"Dragon Bow", pts:25, d:"36\", S6, AP-2. Commanders of the Empire only."},
      {n:"Von Trickschotte's Wondrous Arquebus", pts:25, d:"36\", S5, AP-2. City-state of Nuln only. No -1 modifier for long range."},
    ],
    "dark-elves": [
      {n:"Executioner's Axe", pts:70, d:"S, AP-2. Roll To Wound on 2+ always succeeds."},
      {n:"Sword of Ruin", pts:65, d:"S, *. No armour, Ward or Regeneration saves permitted."},
      {n:"Lifetaker", pts:35, d:"24\", S3, AP-1. Repeater crossbow."},
      {n:"Whip of Agony", pts:30, d:"S+1, AP-1. High Beastmasters only. Enemy hit suffers -1 Toughness (permanent, min 1)."},
    ],
    "high-elf-realms": [
      {n:"Woodsman's Axe", pts:90, d:"S+3, AP-4. Chracian Warhost only."},
      {n:"The White Sword", pts:70, d:"S+3, AP-2. Infantry or chariot only."},
      {n:"The Blade of Leaping Gold", pts:50, d:"S, -. The wielder has the Strike First special rule and +D3 Attacks."},
      {n:"Bow of the Seafarer", pts:50, d:"30\", S5, AP-3. Shoots like a bolt thrower using Through & Through."},
      {n:"Star Lance", pts:45, d:"S+3, AP-4. Cavalry or monster only. Only usable on the turn the wielder charges."},
      {n:"Blade of Sea Gold", pts:40, d:"S+1, AP-1. Sea Guard Garrison only."},
      {n:"Reaver Bow", pts:40, d:"30\", S+1, -. Shots equal to Attacks characteristic; no multiple shots penalty."},
      {n:"Foe Bane", pts:20, d:"S, -. Roll To Wound on 4+ always succeeds."},
    ],
    "kingdom-of-bretonnia": [
      {n:"Sword of the Quest", pts:70, d:"Single-handed: S+1, AP-1. Double-handed: S+2, AP-2."},
      {n:"Crusader's Lance", pts:60, d:"S+2, AP-2. Errantry Crusade only. Cavalry/monster only; charge turn only."},
      {n:"Sword of Heroes", pts:60, d:"S, -. Roll To Wound on 5+ always succeeds."},
      {n:"Heartwood Lance", pts:50, d:"S+3, AP-3. Cavalry/monster only. Charge turn only."},
      {n:"Morning Star of Fracasse", pts:40, d:"S+1, AP-1. Magic weapon of enemy hit: destroyed for the rest of the game."},
      {n:"Frontier Axe", pts:30, d:"S+2, AP-3. Bretonnian Exiles only."},
      {n:"Sword of the Stout Hearted", pts:25, d:"S+2, AP-1."},
      {n:"Foebreaker", pts:20, d:"S+1, -. On hit: enemy makes Toughness test or -1 WS and -1 Attacks until end of next Combat phase."},
    ],
    "lizardmen": [
      {n:"Blade of Revered Tzunki", pts:65, d:"S, AP-2. Attacks made with this weapon have the Killing Blow special rule."},
      {n:"Scimitar of the Sun Resplendent", pts:50, d:"S+1, AP-1. The wielder and any unit they have joined gain the Hatred special rule."},
      {n:"Staff of the Lost Sun", pts:40, d:"S, -. The wielder can cast the Burning Head spell as a Bound Spell (Power Level 3)."},
      {n:"Piranha Blade", pts:35, d:"S+1, AP-3. The wielder has the Armour Bane (D3) special rule."},
    ],
    "ogre-kingdoms": [
      {n:"Thundermace", pts:90, d:"S+4, AP-4. The wielder has the Killing Blow special rule."},
      {n:"Tenderiser", pts:70, d:"S+2, AP-3. The wielder has the Multiple Wounds (D3) special rule."},
      {n:"Skullplucker", pts:45, d:"S, AP-2. The wielder has a +2 modifier to their Attacks characteristic."},
      {n:"Bloodcleaver", pts:30, d:"S+2, AP-2. Each unsaved wound inflicted restores 1 lost Wound to the wielder."},
    ],
    "orc-and-goblin-tribes": [
      {n:"Battleaxe of the Last Big Waaagh!", pts:75, d:"S+3, AP-3. The wielder has the Heroic Killing Blow special rule."},
      {n:"Bigger Choppier Axe", pts:55, d:"S+2, AP-3. The wielder has the Strike First special rule."},
      {n:"Martog's Best Basha", pts:50, d:"S+2, AP-2. The wielder has +D3 Attacks."},
      {n:"Porko's Pigstikka", pts:40, d:"12\", S3, AP-1. Also a melee weapon: S, AP-1."},
      {n:"Da Choppiest Choppa", pts:35, d:"S+1, AP-2. The wielder has Killing Blow."},
      {n:"Da Akrit Axe", pts:30, d:"S, AP-2. The wielder has a +2 modifier to their Strength characteristic."},
      {n:"Backstabber's Blade", pts:25, d:"S, AP-1. Re-roll To Wound against enemy units with a higher Unit Strength. Extremely Common."},
      {n:"Wollopa's One Hit Wunda", pts:15, d:"S+3, AP-3. The wielder can only make 1 attack, regardless of their Attacks characteristic."},
    ],
    "skaven": [
      {n:"Fellblade", pts:100, d:"S+3, AP-5. Heroic Killing Blow. Each To Hit roll of 1 wounds the wielder (no saves)."},
      {n:"Weeping Blade", pts:50, d:"S, AP-2. Hits inflict Poisoned Attacks and Armour Bane (D3)."},
      {n:"Blade of Nurglitch", pts:35, d:"S+1, AP-1. The wielder has the Poisoned Attacks special rule."},
      {n:"Death Globe", pts:25, d:"Template, S2, AP-. Single use; thrown weapon. Extremely Common."},
    ],
    "tomb-kings-of-khemri": [
      {n:"Destroyer of Eternities", pts:75, d:"S+2, AP-3. The wielder has the Heroic Killing Blow special rule."},
      {n:"Conqueror's Blade", pts:55, d:"S+1, AP-1. The wielder has a +1 modifier to their Attacks characteristic and Killing Blow."},
      {n:"Crook & Flail of Radiance", pts:50, d:"S+1, AP-1. +D3 Attacks. Re-roll failed rolls To Hit and To Wound for each extra attack."},
      {n:"Blade of Antarhak", pts:45, d:"S, AP-2. Each unsaved wound inflicted restores 1 lost Wound to the wielder."},
      {n:"Flail of Skulls", pts:35, d:"S+2, AP-2. Flail rules. Multiple Wounds (D3)."},
      {n:"Phakth's Blades of Justice", pts:35, d:"S, AP-1. The wielder has +2 Attacks and Killing Blow."},
      {n:"Staff of Aeons", pts:30, d:"S, AP-. The wielder can cast the Shem's Burning Gaze spell as a Bound Spell (Power Level 3)."},
      {n:"Serpent Staff", pts:20, d:"S, AP-. Attacks have Poisoned Attacks. The wielder can cast a bound snake-related spell."},
    ],
    "vampire-counts": [
      {n:"Frostblade", pts:60, d:"S, -. On wound: enemy makes Toughness test or gains Strike Last and I reduced to 1 permanently."},
      {n:"Sword of Kings", pts:55, d:"S+1, AP-1. Killing Blow on natural 5 or 6 To Wound."},
      {n:"Blood Drinker", pts:45, d:"S, AP-1. Each unsaved wound in Combat restores 1 lost Wound to the wielder."},
      {n:"Dreadlance", pts:40, d:"S+2, AP-2. Cavalry/monster only. Charge turn only. Re-roll failed rolls To Hit."},
    ],
    "wood-elf-realms": [
      {n:"Spear of Twilight", pts:65, d:"S+2, AP-2. The wielder has +2 Attacks."},
      {n:"Vaul's Wrath", pts:55, d:"S, AP-2. The wielder has the Armour Bane (D3) special rule."},
      {n:"Blades of Loec", pts:45, d:"S, AP-1. +3 Attacks. The wielder has the Strike First special rule."},
      {n:"Bow of Loren", pts:40, d:"30\", S3, AP-. Shots equal to Attacks characteristic. No multiple shots penalty."},
      {n:"Daith's Reaper", pts:40, d:"S+1, AP-2. The wielder has the Heroic Killing Blow special rule."},
      {n:"Hunt Master's Pride", pts:35, d:"S+1, AP-1. Enemy models in base contact with the wielder suffer -1 Strength."},
      {n:"Blades of Endless Flame", pts:25, d:"S, AP-1. +1 Attack. Flaming Attacks."},
      {n:"Asyendi's Bane", pts:10, d:"S, AP-. Magical Attacks. The wielder has the Armour Bane (1) special rule."},
    ],
    "empire-of-grand-cathay": [
      {n:"Monkey King's Wisdom", pts:75, d:"S+2, AP-2. +1 Attack. The wielder has the Killing Blow special rule."},
      {n:"Jade Blade of the Great Fleet", pts:70, d:"S+1, AP-3. No armour saves permitted against this weapon."},
      {n:"Sword of Reason", pts:65, d:"S, AP-1. +D3 Attacks. Re-roll failed rolls To Hit."},
      {n:"Brazen Blade", pts:50, d:"S+1, AP-1. Flaming Attacks. Enemy hit must pass a Toughness test or suffers a further wound."},
      {n:"Wrath of Xen Yang", pts:45, d:"S+1, AP-2. +1 Attack. Killing Blow."},
      {n:"Sword of Nan-Gau", pts:35, d:"S, AP-1. The wielder has the Strike First and Strike Last special rules simultaneously."},
      {n:"Spirit Longma Spear", pts:25, d:"S+1, AP-. Cavalry only. On charge: S+2 instead, with Killing Blow."},
      {n:"Sun & Moon Blades", pts:20, d:"S, AP-1. +2 Attacks. Must be used as additional hand weapons."},
    ],
    "dwarfs": [
      {n:"Master Rune of Smiting", pts:75, d:"S+2, AP-3. Killing Blow."},
      {n:"Master Rune of Skalf Blackhammer", pts:65, d:"S+2, AP-2. All unsaved wounds become Multiple Wounds (2)."},
      {n:"Master Rune of Alaric the Mad", pts:45, d:"S, AP-1. No armour, Ward or Regen saves permitted."},
      {n:"Master Rune of Dragon Slaying", pts:35, d:"S, AP-. Multiple Wounds (2) against Large Targets. Heroic Killing Blow."},
      {n:"Rune of Parrying", pts:35, d:"Shield only. Enemies in base contact suffer -1 Weapon Skill."},
      {n:"Master Rune of Breaking", pts:25, d:"S, AP-2. Against models with Ward saves: re-roll To Wound rolls."},
      {n:"Master Rune of Flight", pts:25, d:"S, AP-. Missile weapon: 24\", S5, AP-, multiple shots (3)."},
      {n:"Master Rune of Swiftness", pts:25, d:"S+1, AP-. The wielder has the Strike First special rule."},
      {n:"Rune of Banishment", pts:25, d:"S, AP-. Against Daemons and Undead: wounds on 2+ with no saves."},
      {n:"Rune of Fury", pts:25, d:"S, AP-. +1 Attack. Extremely Common."},
      {n:"Grudge Rune", pts:20, d:"S, AP-. Re-roll failed rolls To Wound. Extremely Common."},
      {n:"Rune of Might", pts:20, d:"S+1, AP-. Extremely Common."},
      {n:"Rune of Cleaving", pts:15, d:"S, AP-1. Extremely Common."},
      {n:"Rune of Striking", pts:15, d:"S, AP-. +1 To Hit in Combat. Extremely Common."},
      {n:"Rune of Fire", pts:10, d:"S, AP-. Flaming Attacks."},
      {n:"Rune of Speed", pts:5, d:"S, AP-. +1 Initiative to wielder. Extremely Common."},
    ],
  },
  armour: {
    "common": [
      {n:"Armour of Destiny", pts:70, d:"Heavy armour + 4+ Ward save."},
      {n:"Bedazzling Helm", pts:60, d:"Infantry/cavalry only. +1 armour value (max 2+). Enemies suffer -1 To Hit against bearer in Combat."},
      {n:"Armour of Silvered Steel", pts:40, d:"Armour value 3+ which cannot be improved in any way."},
      {n:"Glittering Scales", pts:35, d:"Light armour. Once per turn, force opponent to re-roll one To Hit roll against the bearer."},
      {n:"Shield of the Warrior True", pts:30, d:"Shield. 5+ Ward save against wounds in the Shooting phase."},
      {n:"Levitating Shield", pts:25, d:"Infantry only. Shield usable alongside a Requires Two Hands weapon."},
      {n:"Spellshield", pts:25, d:"Shield. 5+ Ward save vs wounds from Magic Missiles, Magical Vortexes, or Assailments. Extremely Common."},
      {n:"Armour of Meteoric Iron", pts:20, d:"Armour value 5+ — cannot be improved OR reduced in any way."},
      {n:"Trailblazer's Hauberk", pts:20, d:"Infantry only. Heavy armour + Move Through Cover + Scouts."},
      {n:"Enchanted Shield", pts:10, d:"Shield. 6+ Ward save vs non-magical attacks. Extremely Common."},
      {n:"Charmed Shield", pts:5, d:"Shield. Single use: 5+ Ward save against one wound, then becomes mundane. Extremely Common."},
    ],
    "beastmen-brayherds": [
      {n:"Full Plate Chaos Armour", pts:40, d:"Full plate armour. May be worn by a Wizard without penalty. 5+ Ward save. Extremely Common."},
      {n:"Pelt of the Dark Young", pts:40, d:"+1 armour value (max 2+). Magic Resistance (-2) for bearer and unit."},
      {n:"Heavy Chaos Armour", pts:30, d:"Heavy armour. May be worn by a Wizard without penalty. 5+ Ward save. Extremely Common."},
      {n:"The Blackened Plate", pts:25, d:"Full plate armour. 3+ Ward save vs Flaming Attacks."},
      {n:"The Fur of Sharggu", pts:20, d:"+2 armour value (max 2+) vs non-magical shooting attacks."},
    ],
    "chaos-dwarfs": [
      {n:"Armour of Bazherak the Cruel", pts:50, d:"Full plate armour. Immune to Psychology. Magic Resistance (-2)."},
      {n:"The Mask of the Furnace", pts:40, d:"+1 armour value (max 2+). 3+ Ward save vs Flaming Attacks."},
    ],
    "warriors-of-chaos": [
      {n:"Armour of the Damned", pts:70, d:"Full plate armour. In Combat, enemies must re-roll successful rolls To Hit against the wearer."},
      {n:"Daemonic Platemail", pts:50, d:"Infantry/cavalry only. Full plate armour. +1 Toughness and +1 Initiative."},
      {n:"Crimson Armour of Dargan", pts:40, d:"Infantry/cavalry only. Heavy armour. Immune to Multiple Wounds (X)."},
      {n:"Mighty Serpent's Scalemail", pts:40, d:"Wolves of the Sea only. Heavy armour. Wearer gains Strike First."},
    ],
    "empire-of-man": [
      {n:"Armour of Fortune", pts:45, d:"Heavy armour. 6+ Ward save. Immune to Killing Blow (takes 1 wound instead)."},
      {n:"Shield of the Gorgon", pts:40, d:"Knightly Order shield only. Enemy in base contact suffers -1 Attacks (min 1)."},
      {n:"Armour of Tarnus", pts:35, d:"Light armour; may be worn by Imperial Wizards. 5+ Ward save."},
      {n:"Twice-Blessed Armour", pts:25, d:"Full plate armour. Bearer can cast Hammerhand as a Bound Spell (PL 2)."},
    ],
    "dark-elves": [
      {n:"Shield of Ghrond", pts:40, d:"Shield. Attacks against bearer suffer -1 Strength (min 1)."},
      {n:"Blood Armour", pts:30, d:"Infantry/cavalry only. Armour value 5+; improves by 1 for each unsaved wound inflicted (max 2+)."},
    ],
    "high-elf-realms": [
      {n:"Armour of Stars", pts:40, d:"Infantry/cavalry only. Heavy armour. Immune to Killing Blow."},
      {n:"Armour of Caledor", pts:35, d:"Full plate armour. 5+ Ward save."},
      {n:"The Golden Shield", pts:30, d:"Shield. Enemies must re-roll rolls To Hit of a natural 6 against the bearer in Combat."},
      {n:"Dragon Helm", pts:10, d:"+1 armour value (max 2+). 6+ Ward save vs Flaming Attacks."},
    ],
    "kingdom-of-bretonnia": [
      {n:"Gilded Cuirass", pts:60, d:"Heavy armour. Regeneration (5+)."},
      {n:"Anointed Armour", pts:45, d:"Grail Vow, infantry/cavalry only. Heavy armour. While Blessed: immune to Killing Blow and Multiple Wounds."},
      {n:"Gromril Great Helm", pts:40, d:"+1 armour value (max 2+). Re-roll natural 1s on Armour Saves."},
      {n:"Ironspike Shield", pts:20, d:"Bretonnian Exiles only. Shield. Opponent rolls 1 To Hit or Wound in combat: suffers S3, AP-1 hit."},
    ],
    "lizardmen": [
      {n:"Shield of the Mirror Pool", pts:40, d:"Shield. 4+ Ward save vs enemy shooting attacks. Enemies suffer -1 To Hit with missile weapons."},
      {n:"Hide of the Cold Ones", pts:20, d:"Heavy armour. Wearer is immune to Fear and Terror."},
    ],
    "ogre-kingdoms": [
      {n:"Gut Maw", pts:45, d:"Heavy armour. When bearer wins a combat, enemy unit in base contact must pass a Panic test."},
      {n:"Mastodon Armour", pts:40, d:"Full plate armour. Wearer has the Armoured Hide (2) special rule."},
    ],
    "orc-and-goblin-tribes": [
      {n:"Trollhide Trousers", pts:40, d:"Full plate armour. Wearer has the Regeneration (5+) special rule. Extremely Common."},
      {n:"Dead 'Ard Armour", pts:35, d:"Full plate armour. Enemies in base contact suffer -1 Weapon Skill."},
      {n:"Armour of Mork", pts:30, d:"Heavy armour. 5+ Ward save vs Magical Attacks."},
      {n:"Spiteful Shield", pts:20, d:"Shield. Enemies in base contact suffer -1 Attacks (min 1)."},
    ],
    "skaven": [
      {n:"Warpstone Armour", pts:25, d:"Full plate armour. At the end of each Combat phase, bearer suffers 1 Strength 4 hit with AP-2. Extremely Common."},
      {n:"Cautious Shield", pts:20, d:"Shield. 5+ Ward save. Bearer loses the Skaven special rules (but keeps other special rules)."},
    ],
    "tomb-kings-of-khemri": [
      {n:"Armour of the Ages", pts:50, d:"Full plate armour. 4+ Ward save. Immune to Multiple Wounds (X)."},
      {n:"Royal Mantle", pts:40, d:"May be worn with other armour. +2 armour value (max 2+). 6+ Ward save."},
      {n:"Warding Splint", pts:35, d:"Heavy armour. 5+ Ward save vs wounds with AP of -1 or lower."},
      {n:"Shield of Ptra", pts:25, d:"Shield. Re-roll failed Armour Saves in the Shooting phase."},
    ],
    "vampire-counts": [
      {n:"The Flayed Hauberk", pts:35, d:"Heavy armour; may be worn by Wizards. 6+ Ward save."},
      {n:"The Accursed Armour", pts:30, d:"Infantry/cavalry only. Full plate armour. +1 Toughness, -1 WS and -1 Initiative (min 1)."},
    ],
    "wood-elf-realms": [
      {n:"Helm of the Hunt", pts:50, d:"May be worn with other armour. +2 armour value (max 2+). Enemies suffer -1 WS in Combat."},
      {n:"Mantle of Rebirth", pts:40, d:"Light armour. Regeneration (4+)."},
      {n:"Railarian's Mantle", pts:35, d:"Light armour. Bearer and unit have the Scouts and Vanguard special rules."},
      {n:"Cloak of Tumbling Leaves", pts:30, d:"Light armour. Bearer has a 5+ Ward save. Enemies suffer -1 To Hit with missile weapons."},
    ],
    "empire-of-grand-cathay": [
      {n:"Armour of the Warbird", pts:45, d:"Heavy armour. Bearer has the Fly (8) special rule."},
      {n:"Jade Armour of Beichai", pts:40, d:"Heavy armour. 5+ Ward save. Magic Resistance (-1)."},
      {n:"Mantle of Heaven", pts:20, d:"Light armour. 5+ Ward save vs magical attacks."},
      {n:"Shield of Nan-Gau", pts:20, d:"Shield. Bearer has 4+ Ward save vs Flaming Attacks."},
    ],
    "dwarfs": [
      {n:"Master Rune of Adamant", pts:100, d:"The wearer has +2 Toughness. Armour value cannot be reduced in any way."},
      {n:"Master Rune of Gromril", pts:45, d:"Armour value 2+. Immune to Killing Blow. Cannot be improved further."},
      {n:"Rune of Iron", pts:35, d:"+1 armour value (max 2+). May be applied to any armour or shield."},
      {n:"Rune of Fortitude", pts:30, d:"The wearer has +1 Wound. Extremely Common."},
      {n:"Rune of Preservation", pts:25, d:"5+ Ward save vs Magical Attacks."},
      {n:"Rune of Shielding", pts:15, d:"+1 armour value (max 2+) on a shield. Extremely Common."},
      {n:"Rune of Stone", pts:5, d:"+1 armour value (max 2+). Extremely Common."},
    ],
  },
  talisman: {
    "common": [
      {n:"Dawnstone", pts:35, d:"Re-roll Armour Save rolls of a natural 1."},
      {n:"Icon of Fortitude", pts:35, d:"Infantry/cavalry only. Immune to Multiple Wounds (X); suffers single wound instead."},
      {n:"Ironhide Talisman", pts:30, d:"Infantry only. Enemies that hit the bearer must re-roll rolls To Wound of a natural 6."},
      {n:"Talisman of Protection", pts:30, d:"5+ Ward save."},
      {n:"Paymaster's Coin", pts:25, d:"Single use. Re-roll all failed rolls To Hit in Combat. Extremely Common."},
      {n:"Obsidian Lodestone", pts:20, d:"Up to 3x. Each gives Magic Resistance (-1). Extremely Common."},
      {n:"Luckstone", pts:15, d:"Single use. Re-roll one failed Armour Save. Extremely Common."},
    ],
    "beastmen-brayherds": [
      {n:"Chalice of Dark Rain", pts:50, d:"Single use. Halves range of all enemy missile weapons and silences war machines until next turn."},
      {n:"Cornucopia of Corpulence", pts:30, d:"When combat is chosen: enemies in base contact must pass a Toughness test or lose 1 Wound."},
      {n:"Rune of the True Beast", pts:30, d:"Enemy monsters within 6\" suffer -1 Weapon Skill."},
      {n:"Dark Heart", pts:25, d:"Single use. Recover 1 lost Wound. Extremely Common."},
    ],
    "chaos-dwarfs": [
      {n:"Mantle of Stone", pts:30, d:"+1 Toughness, -1 Initiative. Extremely Common."},
      {n:"Hellshard", pts:20, d:"When bearer loses last Wound in Combat: attacking unit suffers D6 S5, AP-1 hits."},
    ],
    "warriors-of-chaos": [
      {n:"Talisman of the Carrion Crow", pts:45, d:"Regeneration (5+) and Poisoned Attacks."},
      {n:"Crown of Everlasting Conquest", pts:40, d:"Regeneration (5+)."},
      {n:"Talisman of the Soaring Eagle", pts:35, d:"Magic Resistance (-2). 5+ Ward save vs Magical Attacks."},
      {n:"Brazen Collar", pts:20, d:"Magic Resistance (-2). Extremely Common."},
    ],
    "empire-of-man": [
      {n:"The White Cloak", pts:30, d:"5+ Ward save. 3+ Ward save vs Flaming Attacks."},
      {n:"Jade Amulet", pts:25, d:"Immune to Killing Blow (takes 1 wound instead). Extremely Common."},
      {n:"Witch Hunter's Ward", pts:20, d:"Magic Resistance (-2). Single use: re-roll one failed Armour Save. Extremely Common."},
      {n:"Slayer's Hourglass", pts:10, d:"Enemy monsters in base contact suffer -1 Weapon Skill."},
    ],
    "dark-elves": [
      {n:"Pendant of Khaeleth", pts:40, d:"5+ Ward save vs S4 or lower; 4+ Ward save vs S5 or higher."},
      {n:"Pearl of Infinite Bleakness", pts:15, d:"Bearer and unit gain Immune to Psychology."},
    ],
    "high-elf-realms": [
      {n:"Circlet of Atrazar", pts:55, d:"+1 Wound. Infantry/cavalry only: +1 Toughness."},
      {n:"Sacred Incense", pts:35, d:"Enemies targeting bearer or unit in Shooting phase suffer -1 To Hit."},
      {n:"The Loremaster's Cloak", pts:25, d:"4+ Ward save vs Magic Missiles."},
      {n:"Opal Amulet", pts:20, d:"Single use. 2+ Ward save against a single wound. Extremely Common."},
    ],
    "kingdom-of-bretonnia": [
      {n:"Grail Pendant", pts:40, d:"Grail Vow only. Single use. When bearer loses last Wound, roll D6: on 2+ the Wound is not lost."},
      {n:"Lucky Heirloom", pts:25, d:"Bretonnian Exiles only. Re-roll one failed To Hit, To Wound, Armour Save or Ward Save per round. Extremely Common."},
      {n:"Mantle of the Damsel Elena", pts:25, d:"Immune to Poisoned Attacks (attacker must roll To Wound normally)."},
      {n:"Sirienne's Locket", pts:25, d:"Infantry/cavalry only. Immune to Multiple Wounds (X)."},
    ],
    "lizardmen": [
      {n:"Glyph Necklace", pts:45, d:"5+ Ward save. Magic Resistance (-2)."},
      {n:"Aura of Quetzl", pts:40, d:"4+ Ward save."},
    ],
    "ogre-kingdoms": [
      {n:"Spangleshard", pts:35, d:"5+ Ward save. Once per game, may be used to re-roll a single dice."},
      {n:"Cathayan Jet Pendant", pts:10, d:"Magic Resistance (-1). Extremely Common."},
    ],
    "orc-and-goblin-tribes": [
      {n:"Sparkly Wizard Finda", pts:45, d:"Magic Resistance (-3). Once per Magic phase, may steal a Power or Dispel dice from the opponent."},
      {n:"Effigy of Mork", pts:35, d:"5+ Ward save. When a Wizard within 18\" casts a spell, roll a dice: on 6+ the spell is dispelled automatically."},
      {n:"Glowy Green Amulet", pts:35, d:"4+ Ward save vs Magical Attacks."},
      {n:"Collar of Zorga", pts:20, d:"4+ Ward save vs Poisoned Attacks and Flaming Attacks."},
    ],
    "skaven": [
      {n:"Shadow Magnet", pts:40, d:"Units shooting at bearer or unit suffer -1 To Hit. Enemy cannot nominate bearer as target of spells if another unit is closer."},
      {n:"Warpstone Amulet", pts:35, d:"5+ Ward save. Once per game: re-roll any one dice."},
    ],
    "tomb-kings-of-khemri": [
      {n:"Amulet of the Serpent", pts:30, d:"5+ Ward save. Magic Resistance (-1). Poisoned Attacks for bearer."},
      {n:"Crown of Kings", pts:30, d:"Immune to Psychology. All friendly units within 6\" re-roll failed Ld tests. Extremely Common."},
      {n:"Collar of Shapesh", pts:25, d:"5+ Ward save vs Flaming Attacks."},
      {n:"Relic of the Desert Sun", pts:25, d:"Enemy models in base contact suffer -1 Weapon Skill."},
    ],
    "vampire-counts": [
      {n:"Von Carstein Ring", pts:40, d:"Vampires only. Single use. When bearer loses last Wound, on 2+ the Wound is not lost."},
      {n:"Crown of the Damned", pts:35, d:"4+ Ward save. Wielder gains Stupidity."},
    ],
    "wood-elf-realms": [
      {n:"Merciw's Locus", pts:35, d:"5+ Ward save. Once per game: all friendly units within 12\" may immediately move up to 3\"."},
      {n:"Ariel's Favour", pts:30, d:"5+ Ward save. Bearer and unit have the Immune to Psychology special rule."},
      {n:"Glamourweave", pts:30, d:"4+ Ward save vs Magical Attacks."},
      {n:"Orion's Favour", pts:25, d:"Bearer has the Swiftstride and Vanguard special rules."},
    ],
    "empire-of-grand-cathay": [
      {n:"Crystal of Kunlan", pts:35, d:"5+ Ward save. Once per game: ignore a miscast result."},
      {n:"Sigil of Smoke & Powder", pts:35, d:"5+ Ward save vs Shooting. Enemies targeting bearer or unit suffer -1 To Hit."},
      {n:"Vermilion Quills", pts:25, d:"Once per turn: bearer may re-roll a single failed roll To Hit or To Wound in combat. Extremely Common."},
      {n:"Crown of Jade", pts:20, d:"4+ Ward save vs Magical Attacks."},
    ],
    "dwarfs": [
      {n:"Master Rune of Calm", pts:50, d:"Magic Resistance (-3). The bearer cannot be targeted by spells."},
      {n:"Master Rune of Balance", pts:35, d:"Once per Magic phase: steal one Power dice from the enemy pool."},
      {n:"Master Rune of Spite", pts:35, d:"Each time bearer suffers a wound, enemy model or unit that caused it suffers 1 S4 hit."},
      {n:"Rune of Spellbreaking", pts:25, d:"Single use. Automatically dispel one spell with no roll. Extremely Common."},
      {n:"Rune of Warding", pts:20, d:"5+ Ward save. Extremely Common."},
      {n:"Rune of Luck", pts:15, d:"Single use. Re-roll one dice of your choice. Extremely Common."},
      {n:"Rune of Passage", pts:5, d:"Bearer has Move Through Cover."},
      {n:"Rune of the Furnace", pts:5, d:"Bearer has immunity to Flaming Attacks."},
    ],
  },
  standard: {
    "common": [
      {n:"Banner of Iron Resolve", pts:50, d:"Unit gains Stubborn."},
      {n:"Banner of the Steadfast", pts:50, d:"Infantry only. Unit can Fall Back in Good Order even if outnumbered 2:1."},
      {n:"Totem of Wrath", pts:50, d:"On a charge: +1 AP on all weapons and re-roll rolls To Wound of natural 1."},
      {n:"Razor Standard", pts:40, d:"Unit gains Armour Bane (2)."},
      {n:"Banner of Swirling Wind", pts:30, d:"Enemies shooting at unit suffer -1 To Hit."},
      {n:"Rampaging Banner", pts:30, d:"Re-roll the Charge roll when declaring a charge."},
      {n:"The Blazing Banner", pts:25, d:"Unit gains Flaming Attacks."},
      {n:"Monster Hunter's Tapestry", pts:25, d:"Enemy units cannot make Stomp Attacks against this unit."},
      {n:"War Banner", pts:25, d:"+1 combat result point."},
    ],
    "beastmen-brayherds": [
      {n:"The Gore Banner", pts:50, d:"Enemy units must pass a Ld test to charge a unit carrying this banner."},
      {n:"Totem of Rust", pts:50, d:"Every model within 6\" (friend or foe) suffers -1 on Armour Save rolls."},
      {n:"Banner of the Warped Moon", pts:45, d:"Single use. Pass Ld test: enemy units cannot use Fly until next turn."},
      {n:"The Beast Banner", pts:40, d:"+3\" max charge range and +D3 on Charge rolls."},
      {n:"Manbane Standard", pts:40, d:"All enemy units within 6\" suffer -1 Ld (min 2)."},
      {n:"Vitriolic Totem", pts:30, d:"Unit gains Poisoned Attacks."},
      {n:"Banner of Outrage", pts:25, d:"Re-roll Ld test when testing for Primal Fury."},
      {n:"The Soiled Tapestry", pts:15, d:"Unit gains Hatred (all enemies). All enemies also Hate this unit."},
    ],
    "chaos-dwarfs": [
      {n:"The Lammasu's Beard", pts:65, d:"Unit has 6+ Ward save and Magic Resistance (-2). Friendly units within 6\" have 5+ Ward save vs Shooting and MR(-1)."},
      {n:"Ashen Banner", pts:30, d:"Enemies targeting this unit in Shooting phase suffer -1 To Hit."},
      {n:"Overseer's Sigil", pts:25, d:"Friendly units within 9\" lose the Levies special rule."},
      {n:"Shroud of the Ancestor", pts:10, d:"Unit gains Hatred (Dwarfs)."},
    ],
    "warriors-of-chaos": [
      {n:"Banner of the Gods", pts:75, d:"Unit ignores all negative Ld modifiers."},
      {n:"Doom Totem", pts:65, d:"All enemy units with line of sight suffer -1 Ld."},
      {n:"Banner of the Dark Powers", pts:50, d:"Unit gains Magic Resistance (-3)."},
      {n:"Blasted Standard", pts:40, d:"Unit re-rolls natural 1 Armour Saves in the Shooting phase."},
      {n:"Banner of Rage", pts:35, d:"Unit gains Frenzy which cannot be lost."},
      {n:"Banner of the Baying Hound", pts:25, d:"Heralds of Darkness only. Unit gains Vanguard."},
      {n:"Sea Raider's Crest", pts:25, d:"Wolves of the Sea only. Unit gains Fear (or Terror if already has Fear)."},
      {n:"Icon of Darkness", pts:20, d:"Enemies targeting unit in Shooting phase suffer -1 To Hit."},
    ],
    "empire-of-man": [
      {n:"Banner of the Knights Panther", pts:80, d:"BSB of Order of the Knights Panther only. Unit gains Unbreakable."},
      {n:"Imperial Banner", pts:60, d:"Friendly units within Command range roll 3D6 for Fear/Panic/Terror tests, discard highest."},
      {n:"Griffon Standard", pts:50, d:"Rank Bonus is +2 per rank (instead of +1)."},
      {n:"Tapestry of Sigmar's Triumph", pts:40, d:"Re-roll rolls To Wound of natural 1 in the first round of combat."},
      {n:"Icon of Morr", pts:25, d:"Unit gains Fear (or Terror if already has Fear)."},
      {n:"The Banner of the Free State of Nuln", pts:20, d:"City-state of Nuln only. Unit gains Stubborn."},
      {n:"The Gleaming Pennant", pts:15, d:"Single use. Re-roll one failed Ld test."},
      {n:"Banner of Duty", pts:10, d:"Re-roll failed Rally tests."},
    ],
    "dark-elves": [
      {n:"Banner of Nagarythe", pts:65, d:"Unit gains Stubborn. +1 combat result point."},
      {n:"Standard of Slaughter", pts:40, d:"On the turn it charged: +D3 combat result points."},
      {n:"Banner of Har Ganeth", pts:25, d:"+1 AP on all combat weapons."},
      {n:"Cold-Blooded Banner", pts:20, d:"Single use. Roll extra D6 for any Ld test and discard highest."},
    ],
    "high-elf-realms": [
      {n:"Banner of Resilience", pts:80, d:"+1 Toughness to all models in the unit."},
      {n:"Banner of Arcane Protection", pts:70, d:"Magic Resistance (-3). Friendly units within 6\" gain MR(-1)."},
      {n:"Battle Banner", pts:60, d:"+D3 combat result points."},
      {n:"The Banner of Lothern", pts:55, d:"If unit has thrusting spears: half of 3rd rank can make supporting attacks."},
      {n:"Banner of Balance", pts:25, d:"Enemies in base contact cannot re-roll To Hit or To Wound. Neither can this unit."},
      {n:"Lion Standard", pts:25, d:"Unit automatically passes Fear and Terror tests."},
      {n:"Banner of Confidence", pts:20, d:"No -1 To Hit modifier when making a Stand & Shoot reaction."},
      {n:"Banner of Ellyrion", pts:20, d:"Unit gains Move Through Cover."},
    ],
    "kingdom-of-bretonnia": [
      {n:"Banner of the Lady's Grace", pts:75, d:"Unit ignores all negative Ld modifiers."},
      {n:"Valorous Standard", pts:60, d:"Roll 3D6 for Break tests, discard highest."},
      {n:"Conqueror's Tapestry", pts:40, d:"Captured enemy standards are worth 100 VPs as trophies."},
      {n:"Crusader's Tapestry", pts:40, d:"Errantry Crusade only. Unit gains Frenzy."},
      {n:"Errantry Banner", pts:30, d:"+1 Strength on the charge. Unit gains Impetuous."},
      {n:"Banner of Honourable Warfare", pts:25, d:"Re-roll failed rolls To Hit in first round of combat vs enemies with missile weapons."},
      {n:"Banner of the Zealous Knight", pts:25, d:"Bretonnian Exiles only. Unit gains Vanguard."},
      {n:"Banner of Chalons", pts:20, d:"Enemies cannot declare Stand & Shoot charge reaction against this unit."},
    ],
    "lizardmen": [
      {n:"Sun Standard of Chotec", pts:40, d:"Unit re-rolls rolls To Hit of natural 1 in the Shooting phase."},
      {n:"Skavenpelt Banner", pts:35, d:"Skaven models within 12\" must re-roll passed Ld tests."},
      {n:"Totem of Prophecy", pts:30, d:"Once per game: ignore a Panic test."},
      {n:"Jaguar Standard", pts:20, d:"Unit gains the Scouts and Vanguard special rules."},
    ],
    "ogre-kingdoms": [
      {n:"Dragonhide Banner", pts:45, d:"Unit gains Magic Resistance (-2). 5+ Ward save vs Flaming Attacks."},
      {n:"Rune Maw", pts:40, d:"Once per Magic phase: steal one Power dice from the enemy pool."},
      {n:"Cannibal Totem", pts:30, d:"+1 combat result point for each enemy model eaten (Swallowed Whole)."},
      {n:"Bull Standard", pts:20, d:"+1 Strength on the charge."},
    ],
    "orc-and-goblin-tribes": [
      {n:"Big Red Raggedy Flag", pts:50, d:"Unit gains Frenzy which cannot be lost. When the unit passes a Waaagh! test, all models in the unit gain +1 Attack."},
      {n:"Waaagh! Banner", pts:40, d:"Once per game: unit automatically passes a single Waaagh! test."},
      {n:"Da Angry Ladz Flag", pts:35, d:"+1 Strength to all models in the unit."},
      {n:"Da Banner of Butchery", pts:35, d:"Unit re-rolls To Wound rolls of natural 1."},
      {n:"Da Spider Banner", pts:35, d:"Unit gains Poisoned Attacks and Move Through Cover."},
      {n:"Da Banner of Da Nomadz", pts:25, d:"Unit gains Vanguard and Move Through Cover."},
      {n:"Banner of the Wildz", pts:20, d:"Unit gains Move Through Cover."},
      {n:"Guff's Windy Banner", pts:20, d:"Unit gains Flaming Attacks."},
    ],
    "skaven": [
      {n:"Storm Banner", pts:65, d:"Once per game during the Command phase: until next turn, all flying units cannot fly and all non-magical missiles and artillery shots are resolved at -2 Strength."},
      {n:"Grand Banner of Superiority", pts:50, d:"+D3 combat result points."},
      {n:"Dwarf Hide Banner", pts:40, d:"Unit gains Hatred (Dwarfs). Dwarfs within 12\" suffer -1 Ld."},
      {n:"Banner of Verminous Scurrying", pts:35, d:"Unit gains Scouts and Vanguard."},
    ],
    "tomb-kings-of-khemri": [
      {n:"Standard of the Cursing Word", pts:80, d:"Once per game: curse an enemy unit within 12\". Until next turn, that unit re-rolls successful rolls To Hit against this unit."},
      {n:"Icon of the Sacred Eye", pts:50, d:"Unit re-rolls failed rolls To Hit in the Shooting phase."},
      {n:"Royal Standard of Settra", pts:50, d:"Unit gains Stubborn. +1 combat result point."},
      {n:"Sigil of Centuries", pts:45, d:"All models in the unit have +1 Wound on their profile."},
      {n:"Icon of Rakaph", pts:40, d:"+1 Strength and +1 Attacks to all models in the unit."},
      {n:"Tapestry of Conquered Lands", pts:35, d:"Enemies within 12\" suffer -1 Ld."},
      {n:"Banner of the Desert Winds", pts:30, d:"+3\" maximum charge range and re-roll Charge rolls."},
      {n:"Mirage Banner", pts:20, d:"Enemies suffer -1 To Hit against this unit."},
    ],
    "vampire-counts": [
      {n:"Banner of the Barrows", pts:65, d:"Wight Lord BSB only. In Combat: all To Hit rolls of 3+ succeed regardless of enemy WS."},
      {n:"Drakenhof Banner", pts:50, d:"If unit has Regeneration, improves armour value of Regen save by 1."},
      {n:"The Screaming Banner", pts:45, d:"Enemy Ld tests due to Fear caused by this unit: roll extra D6 and discard lowest."},
      {n:"Standard of Hellish Vigour", pts:40, d:"Unit gains Reserve Move."},
    ],
    "wood-elf-realms": [
      {n:"Tapestry of Talsyn", pts:80, d:"Unit gains Stubborn. Once per game: all friendly units within 12\" may immediately Rally."},
      {n:"Banner of the Wildwood", pts:40, d:"+1 Strength to all models in the unit."},
      {n:"Banner of the Hunter King", pts:25, d:"Unit gains Scouts and Vanguard."},
      {n:"Banner of the Wild Hunt", pts:25, d:"+3\" max charge range and +D3 on Charge rolls."},
      {n:"Standard of Morning's Chill", pts:25, d:"Enemies in base contact suffer -1 Initiative."},
      {n:"Banner of Springtide", pts:20, d:"Unit gains Move Through Cover."},
      {n:"Banner of the Eternal Queen", pts:20, d:"Unit re-rolls To Hit rolls of natural 1."},
      {n:"Banner of Midsummer's Eve", pts:15, d:"+1 combat result point."},
    ],
    "empire-of-grand-cathay": [
      {n:"Standard of Wei-Jin", pts:60, d:"Unit gains Stubborn. +1 Strength on the charge."},
      {n:"Banner of the Dragon's Wrath", pts:45, d:"+D3 combat result points."},
      {n:"Icon of Heavenly Fury", pts:45, d:"Unit gains Frenzy. When unit charges: all models gain Killing Blow."},
      {n:"Jade Banner", pts:40, d:"Unit gains Magic Resistance (-2). 5+ Ward save vs Magical Attacks."},
      {n:"Dragon's Eye Banner", pts:30, d:"Enemies within 12\" suffer -1 Ld."},
      {n:"Banner of the Bastion", pts:25, d:"Unit re-rolls failed Armour Saves in the Shooting phase."},
      {n:"Shroud of Shiyama", pts:25, d:"Enemies targeting unit in Shooting phase suffer -1 To Hit."},
      {n:"Banner of Xen Wun", pts:15, d:"Unit gains Vanguard."},
    ],
    "dwarfs": [
      {n:"Master Rune of Grungni", pts:80, d:"Unit has 5+ Ward save vs Shooting. Friendly units within 6\" have 6+ Ward save vs Shooting."},
      {n:"Master Rune of Stromni Redbeard", pts:75, d:"Unit gains Unbreakable."},
      {n:"Master Rune of Hesitation", pts:45, d:"Enemy units must pass a Ld test to declare a charge against this unit."},
      {n:"Rune of Confusion", pts:35, d:"Enemy units within 6\" suffer -1 Ld."},
      {n:"Rune of Fear", pts:30, d:"Unit gains Fear."},
      {n:"Rune of Battle", pts:25, d:"+1 combat result point."},
      {n:"Strollaz' Rune", pts:25, d:"Unit gains Vanguard."},
      {n:"Rune of Courage", pts:15, d:"Unit re-rolls failed Panic tests."},
    ],
  },
  enchanted: {
    "common": [
      {n:"Wizarding Hat", pts:45, d:"Wearer becomes a Level 1 Wizard knowing 1 random spell but gains Stupidity."},
      {n:"Arch-Lightning Rod", pts:40, d:"Single use. Pass Ld test: enemy units cannot use Fly until next turn."},
      {n:"Flying Carpet", pts:40, d:"Regular/heavy infantry only. Bearer gains Fly (8) and Swiftstride but cannot join a unit."},
      {n:"Healing Potion", pts:35, d:"Single use. Recover D3 lost Wounds. Extremely Common."},
      {n:"Ruby Ring of Ruin", pts:35, d:"Cast Fireball (Battle Magic) as a Bound Spell (Power Level 1)."},
      {n:"Potion of Fervour", pts:30, d:"Single use. Until end of turn: +D3 Attacks (max 10)."},
      {n:"Potion of Strength", pts:25, d:"Single use. Until end of turn: +D3 Strength (max 10). Extremely Common."},
      {n:"Becalming Orb", pts:20, d:"Single use. Bound Spell (PL 1): enemy Wizards within 15\" must add 2 to casting value until next turn."},
      {n:"Potion of Toughness", pts:20, d:"Single use. Until end of turn: +D3 Toughness (max 10). Extremely Common."},
      {n:"Potion of Speed", pts:10, d:"Single use. Until end of turn: +D3 Initiative (max 10). Extremely Common."},
      {n:"Potion of Foolhardiness", pts:5, d:"Single use. Until end of turn: bearer gains Immune to Psychology. Extremely Common."},
    ],
    "beastmen-brayherds": [
      {n:"Stone of Spite", pts:45, d:"Single use. All Wizards (friend and foe) suffer -2 to Casting rolls until next turn."},
      {n:"Horn of the Great Hunt", pts:35, d:"Once per turn: +1 or -1 modifier to Ambushers arrival roll."},
      {n:"Horn of the First Beast", pts:30, d:"Friendly units within 18\" may use bearer's Ld for Primal Fury tests."},
      {n:"Scourge of the Burdened", pts:25, d:"Cast Call of the Wild (Lore of Primal Magic) as Bound Spell (PL 2)."},
      {n:"Cacophonous Dirge", pts:15, d:"Enemy musicians within 18\" of bearer's unit cannot use their rules."},
      {n:"Skin of Man", pts:15, d:"Infantry Chieftains/Shamans only. Bearer gains Scouts and Vanguard."},
    ],
    "chaos-dwarfs": [
      {n:"Daemonic Familiar", pts:30, d:"Enemy models in combat with bearer must reduce Ward and Regen save by 1 (min 6+)."},
      {n:"Breath of Hashut", pts:25, d:"Single use. Breath weapon: S4, AP-2."},
      {n:"Obsidian Vambraces", pts:15, d:"+1 Strength and Magic Resistance (-1). Natural 1 To Hit in Combat: vambraces shatter."},
    ],
    "warriors-of-chaos": [
      {n:"Bloodskull Pendant", pts:45, d:"Infantry only. Instead of normal attacks: inflict S8, AP-1, Killing Blow hit on every enemy in base contact."},
      {n:"Rod of the Damned", pts:40, d:"Cast The Summoning (Lore of Daemonology) as Bound Spell (PL 2)."},
      {n:"Daemon-Forged Barding", pts:35, d:"Cavalry only (Heralds of Darkness). On charge: mount and unit mounts gain +1 Attack."},
      {n:"Pendant of Damnation", pts:30, d:"Infantry/cavalry only. +1 Attack for each Wound lost."},
      {n:"Helm of Many Eyes", pts:20, d:"Wearer gains Strike First but also Stupidity."},
      {n:"Favour of the Gods", pts:5, d:"Single use. Re-roll D6 on the Gaze of the Gods table. Extremely Common."},
    ],
    "empire-of-man": [
      {n:"Laurels of Victory", pts:40, d:"Each unsaved wound caused by bearer counts as 2 combat result points."},
      {n:"Squintsoffen's Marvellous Magnifier", pts:35, d:"City-state of Nuln only. No -1 To Hit modifier when shooting at Long Range. Extremely Common."},
      {n:"Ring of Fortune", pts:20, d:"Single use. Re-roll failed rolls To Wound in Combat."},
      {n:"Ring of Taal", pts:20, d:"Single use. Cast Oaken Shield (Battle Magic) as Bound Spell (PL 3)."},
      {n:"The Silver Horn", pts:15, d:"Characters with Swiftstride only. Re-roll D6 when using Swiftstride."},
      {n:"Shroud of Iron", pts:10, d:"Bearer and unit have 6+ Ward save vs non-magical templates."},
    ],
    "dark-elves": [
      {n:"Black Dragon Egg", pts:35, d:"Single use. Until end of turn: Toughness 6 and noxious breath."},
      {n:"Hydra's Tooth", pts:30, d:"9\", S(bearer's S), AP-3. Can target a specific model in a unit."},
      {n:"The Guiding Eye", pts:25, d:"Single use. Re-roll failed rolls To Hit in the Shooting phase."},
    ],
    "high-elf-realms": [
      {n:"Null Stone", pts:75, d:"All Wizards within Command range suffer -1 to Casting and Dispel rolls. Pass Ld test: bearer cannot be targeted by spells until next turn."},
      {n:"Amulet of the Tempest", pts:50, d:"Sea Guard Garrison only. Enemy Wizards within 9\" cannot add Level of Wizardry to Casting rolls."},
      {n:"The Cloak of Beards", pts:30, d:"Wearer causes Terror but other models cannot use bearer's Ld."},
      {n:"Ring of Fury", pts:25, d:"Cast Hammerhand (Battle Magic) as Bound Spell (PL 1). Extremely Common."},
      {n:"Seed of Rebirth", pts:20, d:"Regeneration (5+). Extremely Common."},
      {n:"Gem of Courage", pts:15, d:"Chracian Warhost only. Single use. Re-roll Break test and discard highest D6. Extremely Common."},
    ],
    "kingdom-of-bretonnia": [
      {n:"Falcon-horn of Fredemund", pts:40, d:"Single use. Pass Ld test: enemy units cannot use Fly until next turn."},
      {n:"The Seal of Parravon", pts:35, d:"To Hit roll of 3+ always succeeds regardless of enemy Weapon Skill."},
      {n:"Antlers of the Great Hunt", pts:25, d:"If mounted on a Warhorse: bearer and unit gain Move Through Cover."},
      {n:"Crusader's Clarion", pts:25, d:"Errantry Crusade only. On charge: bearer's mount and unit mounts gain +1 Strength."},
      {n:"Wyrmbreath Vial", pts:20, d:"Bretonnian Exiles only. Single use. Breath weapon: S4, AP-1."},
      {n:"Gauntlet of the Duel", pts:5, d:"Challenges issued by bearer cannot be refused. Extremely Common."},
    ],
    "lizardmen": [
      {n:"Cloak of Feathers", pts:40, d:"Bearer gains Fly (10) and Swiftstride special rules."},
      {n:"Venom of the Firefly Frog", pts:15, d:"Single use. Applied to bearer's weapon: Poisoned Attacks and Flaming Attacks for the rest of the game."},
      {n:"Horned One", pts:10, d:"Bearer has the Armoured Hide (1) special rule. Extremely Common."},
    ],
    "ogre-kingdoms": [
      {n:"Jade Lion", pts:25, d:"Enemy models in base contact with bearer suffer -1 to their Weapon Skill."},
      {n:"Daemon-Slayer Scars", pts:20, d:"Bearer has Magic Resistance (-2). Extremely Common."},
      {n:"Fistful of Laurels", pts:15, d:"Once per combat: bearer may re-roll all failed rolls To Hit. Extremely Common."},
    ],
    "orc-and-goblin-tribes": [
      {n:"Big Boss 'At", pts:50, d:"Wearer gains Inspiring Presence (18\") and General special rule if they are a Big Boss."},
      {n:"Necklace of Blessed Teef", pts:50, d:"5+ Ward save. Once per game: re-roll any single dice."},
      {n:"Grisly Trophy Rack", pts:30, d:"Enemies within 12\" suffer -1 Ld. +1 Attacks to bearer."},
      {n:"Da Thinkin' Orc's 'At", pts:25, d:"Bearer gains the Loner special rule but can re-roll Waaagh! tests."},
      {n:"'Eadbuttin' 'At", pts:15, d:"Orc Bosses/Warbosses only. Bearer has the Headbutt attack. Extremely Common."},
      {n:"Fungus Wine", pts:10, d:"Single use. Until end of turn: bearer has +D6 Attacks but must re-roll successful To Hit rolls. Extremely Common."},
    ],
    "skaven": [
      {n:"Brass Orb", pts:50, d:"Single use. Thrown at enemy unit: S6, AP-3, Multiple Wounds (D3) hits equal to 2D6."},
      {n:"Skalm", pts:35, d:"Once per turn: recover 1 lost Wound. Can only be used 3 times."},
      {n:"Skavenbrew", pts:20, d:"Single use. Until end of turn: bearer has +D6 Attacks but suffers D6 S4 hits at start of each combat. Extremely Common."},
    ],
    "tomb-kings-of-khemri": [
      {n:"Cloak of the Dunes", pts:50, d:"Infantry only. Bearer gains the Ethereal special rule."},
      {n:"Staff of Awakening", pts:50, d:"Once per Command phase: raise D6+2 Skeleton Warriors in a friendly unit within 12\"."},
      {n:"Orb of Ptra", pts:40, d:"Bearer can cast Khsar's Incantation of the Desert Wind as a Bound Spell (PL 3)."},
      {n:"Icon of Rulership", pts:35, d:"Enemy models within 6\" of bearer suffer -1 Ld. Extremely Common."},
      {n:"Death Mask of Kharnutt", pts:20, d:"Bearer causes Terror."},
    ],
    "vampire-counts": [
      {n:"Helm of Commandment", pts:40, d:"Necromancers and Wights only. Pass Ld test: until next turn, bearer and unit gain +D3 Weapon Skill."},
      {n:"Hand of Dust", pts:35, d:"Necromancers only. Assailment Bound Spell (PL 2): target suffers 2D6 S5, AP-1 hits. Roll D6: on 1 the item crumbles."},
      {n:"Cloak of Mist & Shadows", pts:30, d:"Necromancer infantry only. Wearer gains the Ethereal special rule."},
    ],
    "wood-elf-realms": [
      {n:"Wraithstone", pts:50, d:"Enemies within 6\" suffer -1 Weapon Skill and -1 Strength."},
      {n:"Crown of Antlers", pts:35, d:"Bearer has the Terror special rule. Friendly units within 12\" re-roll failed Fear tests."},
      {n:"Hail of Doom Arrow", pts:35, d:"Single use. Fires 3D6 arrows at S3, AP-. Extremely Common."},
      {n:"Moonstone of the Hidden Ways", pts:30, d:"Once per game: bearer and unit can be removed from play and redeployed anywhere within 12\" of their original position."},
      {n:"Wailing Arrow", pts:20, d:"Single use. 30\", S1, AP-. All units (friend and foe) within 12\" of target must pass Panic test. Extremely Common."},
      {n:"Blight-Tipped Arrows", pts:15, d:"Single use. 30\", S3, AP-. Poisoned Attacks. Extremely Common."},
    ],
    "empire-of-grand-cathay": [
      {n:"Maw Shard", pts:50, d:"Once per combat: bearer may re-roll all failed rolls To Wound."},
      {n:"Alchemist's Mask", pts:35, d:"Bearer and unit are immune to Poisoned Attacks and Flaming Attacks."},
      {n:"Ring of Jet", pts:30, d:"Cast a magic missile as a Bound Spell (PL 2): 24\", S4, AP-1."},
      {n:"Golden Lion", pts:25, d:"Bearer and unit within 6\" gain the Stubborn special rule."},
      {n:"Spirit Lantern", pts:25, d:"Bearer has the Ethereal special rule. Extremely Common."},
      {n:"Fires of Nan-Gau", pts:20, d:"Once per game: Flaming Attacks for the rest of the game. Extremely Common."},
    ],
  },
  arcane: {
    "common": [
      {n:"Feedback Scroll", pts:60, d:"Single use. Use instead of Wizardly Dispel. Spell cast normally; then roll 2D6: each 4+ costs casting Wizard 1 Wound."},
      {n:"Scroll of Transmogrification", pts:50, d:"Single use. Use instead of Wizardly Dispel. Spell resolved normally; casting Wizard rolls vs their Level or turns into a frog. Extremely Common."},
      {n:"Wand of Jet", pts:45, d:"+1 to Casting and Dispel rolls. Any natural double destroys the Wand."},
      {n:"Staff of Quietude", pts:35, d:"Pass Ld test: all Remains in Play spells are dispelled (including friendly ones)."},
      {n:"Lore Familiar", pts:30, d:"Do not randomly generate spells; choose freely from chosen lore (including signature)."},
      {n:"Scroll of Disruption", pts:30, d:"Once per turn: re-roll a Dispel roll."},
      {n:"Tome of Spellcraft", pts:30, d:"Once per turn: re-roll a Casting roll."},
      {n:"Dispel Scroll", pts:20, d:"Single use. When dispelling: roll extra D6, discard lowest. Double 1 on any two dice = outclassed. Extremely Common."},
      {n:"Power Scroll", pts:20, d:"Single use. When casting: roll extra D6, discard lowest. Double 1 on any two dice = miscast. Extremely Common."},
      {n:"Arcane Familiar", pts:15, d:"Know spells from two Lores of Magic. Roll for each lore separately."},
      {n:"Earthing Rod", pts:5, d:"Single use. Re-roll a Miscast table result."},
    ],
    "beastmen-brayherds": [
      {n:"The Plague Chalice", pts:40, d:"Any natural double on Casting roll (not double 1): auto-cast as perfect invocation, but bearer suffers S4 hit."},
      {n:"Blood of the Shadowgave", pts:35, d:"Single use. Use instead of dispel: spell auto-dispelled (not perfect invocations). Extremely Common."},
      {n:"Daemon Heart", pts:30, d:"When dispelling: count Level of Wizardry as one higher than the casting Wizard."},
      {n:"Hagtree Fetish", pts:30, d:"Re-roll failed rolls To Wound when casting a successful Magic Missile."},
      {n:"Goretooth", pts:15, d:"In addition to normal lores: may also know spells from Lore of Primal Magic. Extremely Common."},
      {n:"Jagged Dagger", pts:15, d:"Before Casting roll: sacrifice a model from bearer's unit. Add its Wounds to Casting roll (not a modifier vs double 1)."},
    ],
    "chaos-dwarfs": [
      {n:"Daemon Flask", pts:50, d:"Single use. Open during Command phase: all enemy units within Command range must make a Panic test."},
      {n:"Vial of Lammasu Blood", pts:40, d:"Single use. Automatically dispel a spell (not perfect invocations)."},
      {n:"Scroll of Binding", pts:30, d:"Single use. Roll 3D6 for Casting roll. Double 1 on any two = miscast. Extremely Common."},
    ],
    "warriors-of-chaos": [
      {n:"Skull of Katam", pts:60, d:"Bearer and all other Wizards within 3\" (friend or foe) gain +1 to Casting rolls."},
      {n:"Sceptre of Power", pts:55, d:"+1 to Casting and Dispel rolls. Any natural double: bearer suffers S10, AP-3 hit."},
      {n:"Grimoire of Ogvold", pts:50, d:"Know all 7 spells from chosen lore (including signature). Can still only cast Level-number of spells per turn."},
      {n:"Infernal Puppet", pts:50, d:"Enemy Wizards within 15\" who cast must roll extra D6 and discard highest."},
      {n:"Tome of the Dark Gods", pts:35, d:"Mark of Chaos Undivided only. Discard any generated spells to select any Lore of Chaos spell."},
      {n:"Spell Familiar", pts:15, d:"+1 spell known (no Level increase). Extremely Common."},
    ],
    "empire-of-man": [
      {n:"Book of Ashur", pts:85, d:"+3\" Dispel range. Unless rolling a natural double: +1 to Casting/Dispel rolls."},
      {n:"Twin-Tailed Wand", pts:40, d:"Once per turn: attempt to cast a spell a second time. Miscast = D3 wounds (no armour/regen saves)."},
      {n:"Wizard's Familiar", pts:35, d:"+1 to all Dispel rolls. Extremely Common."},
      {n:"Tome of Midnight", pts:30, d:"+1 to Casting rolls for Daemonology, Dark Magic or Necromancy. Know 1 more spell. Loner special rule."},
      {n:"Crystal Ball", pts:20, d:"Once per turn: opponent re-rolls one To Hit or To Wound roll against a friendly character within bearer's Command range."},
      {n:"Wizard's Staff", pts:20, d:"+1 to Casting rolls for Assailment or Magic Missile spells. Extremely Common."},
    ],
    "dark-elves": [
      {n:"Black Staff", pts:55, d:"When casting: roll extra D6, discard lowest. Double 1 on any two = miscast."},
      {n:"Tome of Furion", pts:15, d:"Know 1 more spell than normal for Level of Wizardry."},
      {n:"Focus Familiar", pts:10, d:"Single use. Place marker within 12\": range of next spell measured from marker, not caster. Extremely Common."},
    ],
    "high-elf-realms": [
      {n:"The Vortex Shard", pts:50, d:"Single use. Auto-dispel a spell. Also dispels all Remains in Play spells (including friendly)."},
      {n:"Sigil of Asuryan", pts:40, d:"Single use. Auto-dispel a spell (not perfect invocations). Extremely Common."},
      {n:"The Trickster's Pendant", pts:40, d:"Single use. When dispelling: roll extra D6, discard lowest. Success: casting Wizard cannot cast more spells this turn."},
      {n:"Annulian Crystal", pts:30, d:"Upon successfully casting a spell: may forget it and generate a new one immediately."},
      {n:"Silvery Wand", pts:15, d:"+1 spell known (no Level increase)."},
      {n:"Staff of Solidity", pts:15, d:"Single use. Once per game: may choose not to roll on the Miscast table."},
    ],
    "kingdom-of-bretonnia": [
      {n:"Heart of the Wilds", pts:40, d:"+1 to Casting rolls whilst in a natural terrain feature (woods, difficult/dangerous terrain, not constructions)."},
      {n:"Diadem of Power", pts:35, d:"Errantry Crusade only. +1 to Casting rolls when casting Magical Vortex, Magic Missile or Assailment spells."},
      {n:"Silver Mirror", pts:35, d:"Single use. Dispel attempt: extra D6, discard lowest. On success: casting Wizard suffers S4, AP-2 hit."},
      {n:"Sacrament of the Lady", pts:30, d:"Single use. +2 to next Casting roll. Extremely Common."},
      {n:"Prayer Icon of Quenelles", pts:25, d:"+3\" Dispel range. +1 to Dispel rolls against Hex spells."},
      {n:"Flamestrike Wand", pts:15, d:"Bretonnian Exiles only. Single use. Cast Fireball (Battle Magic) as Bound Spell (PL 3)."},
    ],
    "lizardmen": [
      {n:"Cupped Hands of the Old Ones", pts:55, d:"Single use. Re-roll any single dice in the game before it is resolved."},
      {n:"Cube of Darkness", pts:50, d:"Single use. Remove from play: dispel all spells currently in play including Remains in Play spells. Extremely Common."},
      {n:"Itxi Grub", pts:30, d:"Single use. +D3 to next Casting roll. Extremely Common."},
    ],
    "ogre-kingdoms": [
      {n:"Grut's Sickle", pts:40, d:"Each time bearer successfully casts a spell: one enemy model in base contact suffers D3 S4, AP-2 hits."},
      {n:"Halfling Cookbook", pts:30, d:"+1 to Casting rolls for all spells from the Lore of the Great Maw."},
      {n:"Hellheart", pts:20, d:"Single use. All enemy Wizards within 12\" lose their highest-level spell."},
    ],
    "orc-and-goblin-tribes": [
      {n:"Staff of Baduumm", pts:55, d:"Bearer generates +D3 Power dice at the start of each Magic phase."},
      {n:"Glittering Wotnots", pts:40, d:"Enemy Wizards within 18\" cannot use their Level of Wizardry as a bonus to Dispel rolls."},
      {n:"Idol of Gork", pts:40, d:"Cast a Waaagh! Magic spell as a Bound Spell (PL 3)."},
      {n:"Buzgob's Knobbly Staff", pts:35, d:"+1 to Casting rolls. Once per game: re-roll a failed Casting roll."},
      {n:"Idol of Mork", pts:30, d:"Cast a Waaagh! Magic spell as a Bound Spell (PL 2)."},
      {n:"Da Hag's Brew", pts:25, d:"Single use. D6: 1-2 miscast, 3-4 +1 Power dice, 5-6 +D3 Power dice."},
    ],
    "skaven": [
      {n:"Warp Condenser", pts:50, d:"+D3 Power dice at the start of each Magic phase. Each dice used this way: bearer suffers 1 S4 hit."},
      {n:"Storm Daemon", pts:30, d:"Once per Magic phase: re-roll any one dice used in a Casting or Dispel roll."},
      {n:"Warpstone Tokens", pts:15, d:"Up to 3x. Each token can be spent for +1 to a Casting roll. If result is 12+ after the bonus, bearer suffers a Strength 4 hit. Extremely Common."},
    ],
    "tomb-kings-of-khemri": [
      {n:"Phazerkakt's Kanopi", pts:40, d:"+1 to Casting rolls for all Lore of Nehekhara spells."},
      {n:"Enkhil's Kanopi", pts:30, d:"Once per game: all Remains in Play spells are dispelled."},
      {n:"Hieratic Jar", pts:25, d:"Single use. +3 to next Casting roll. Extremely Common."},
      {n:"Curse-Weaver Wand", pts:20, d:"Once per turn: curse an enemy model within 18\" — until next turn it must re-roll natural 6s To Hit against the bearer."},
      {n:"Scarab Brooch", pts:20, d:"Magic Resistance (-1). Bearer and unit have the Immune to Psychology special rule."},
      {n:"Tablets of Tahoth", pts:20, d:"Know 1 more spell. Extremely Common."},
    ],
    "vampire-counts": [
      {n:"Skull Staff", pts:50, d:"+3\" Dispel range. +1 to Dispel rolls."},
      {n:"Sceptre of de Noirot", pts:35, d:"May use Invocation of Nehek twice per Command phase. Each use: roll D6, on 1 lose 1 Wound."},
      {n:"Spell Familiar", pts:15, d:"+1 spell known (no Level increase). Extremely Common."},
    ],
    "wood-elf-realms": [
      {n:"Deepwood Sphere", pts:45, d:"Once per Magic phase: nominate a spell from any lore — that spell cannot be cast this phase."},
      {n:"Oaken Stave", pts:40, d:"+1 to Casting rolls whilst in a wood. +D3 Power dice whilst in a wood."},
      {n:"Orb of Midsummer", pts:35, d:"Single use. Dispel all Remains in Play spells (friend and foe)."},
      {n:"Wand of Wych Elm", pts:30, d:"+1 to Casting rolls for Lore of Athel Loren spells."},
      {n:"Sigil of the Mage Queen", pts:25, d:"Once per game: bearer may re-roll all their Casting dice."},
      {n:"Heartwood Pendant", pts:15, d:"+1 spell known (no Level increase). Extremely Common."},
    ],
    "empire-of-grand-cathay": [
      {n:"Cloak of Po Mei", pts:50, d:"Bearer cannot be targeted by enemy spells. All Wizards within Command range gain +1 to Casting rolls."},
      {n:"Clockwork Compass", pts:50, d:"Once per game: at the start of any turn, move bearer and unit up to their full Movement distance ignoring terrain and other models."},
      {n:"Guardian Feng Shi Bo", pts:35, d:"Once per game: automatically dispel a spell targeting bearer or their unit. Extremely Common."},
      {n:"Seal of Xing Po", pts:35, d:"Once per turn: after enemy casts a spell, bearer may attempt to steal D3 Dispel dice. Extremely Common."},
      {n:"Learned Feng Shi Bo", pts:15, d:"+1 spell known. Extremely Common."},
      {n:"Scrolls of Wei-jin", pts:10, d:"Bearer has the Lore Familiar item's effect for one spell of their choice."},
    ],
    "dwarfs": [
      {n:"Master Rune of Immolation", pts:30, d:"When bearer is removed as casualty in combat: bearer and enemy unit both suffer D6 S5 Flaming hits."},
      {n:"Master Rune of Disguise", pts:25, d:"Bearer and unit gain the Scouts special rule."},
      {n:"Rune of Skewering", pts:20, d:"+1 to Ballistic Skill for bearer or a war machine."},
      {n:"Rune of Forging", pts:15, d:"Re-roll misfires for a war machine. Extremely Common."},
      {n:"Rune of Burning", pts:10, d:"Bearer or a war machine gains Flaming Attacks."},
      {n:"Rune of Reloading", pts:5, d:"War machine may re-roll Jam results."},
      {n:"Stalwart Rune", pts:5, d:"+1 to Armour Saves for bearer."},
    ],
  },
  ability: {
    "warriors-of-chaos": [
      {n:"Dark Majesty", pts:50, d:"Enemies making Fear or Terror tests within bearer's Command range suffer -1 Ld (min 2)."},
      {n:"Daemon-flesh", pts:45, d:"Cannot be wounded on a roll of 2, regardless of Strength."},
      {n:"Extra Arm", pts:40, d:"+1 Attacks (not mount)."},
      {n:"Diabolic Splendour", pts:35, d:"Infantry/cavalry only. Enemies targeting bearer or their unit in Shooting suffer -1 To Hit."},
      {n:"Enchanting Aura", pts:35, d:"Infantry/cavalry only. Enemies engaged in combat cannot use Strike First; others gain Strike Last."},
      {n:"Aura of Pain", pts:30, d:"Once per game: when bearer's combat is chosen, one enemy unit in contact suffers D6 S3 hits."},
      {n:"Master of Mortals", pts:25, d:"Friendly Chaos Marauders and Marauder Horsemen within Command range gain +1 Ld (max 10)."},
      {n:"Acid Ichor", pts:15, d:"For each Wound bearer loses in a challenge: enemy suffers S4, AP-2 hit."},
      {n:"Poisonous Slime", pts:15, d:"Bearer has Poisoned Attacks (not mount)."},
    ],
    "daemons-of-chaos-khorne": [
      {n:"Spell Eater", pts:50, d:"Bearer may attempt Wizardly Dispel as if Level 2 Wizard."},
      {n:"Armour of Khorne", pts:40, d:"Heavy armour. 5+ Ward save."},
      {n:"Axe of Khorne", pts:35, d:"S+1, AP-1. Extremely Common."},
      {n:"Collar of Khorne", pts:25, d:"+1 Magic Resistance. Extremely Common."},
      {n:"Might of Khorne", pts:25, d:"+1 Strength."},
    ],
    "daemons-of-chaos-nurgle": [
      {n:"Nurgling Infestation", pts:45, d:"Great Unclean One only. D6 additional attacks in combat at I2, WS2, S2. On last Wound: place D3 Nurgling Swarms."},
      {n:"Sloppity Bilepiper", pts:35, d:"Daemonic Heralds infantry only. Friendly Daemons of Nurgle within Command range gain +1 Movement."},
      {n:"Spoilpox Scrivener", pts:30, d:"Daemonic Heralds infantry only. Friendly Daemons of Nurgle within Command range re-roll To Hit rolls of 1."},
      {n:"Trappings of Nurgle", pts:30, d:"Armour value 4+ which cannot be improved in any way."},
      {n:"Stream of Contagion", pts:25, d:"S3, AP-2 breath weapon. Extremely Common."},
    ],
    "daemons-of-chaos-slaanesh": [
      {n:"Infernal Enrapturess", pts:50, d:"Daemonic Heralds infantry only. Friendly Daemons of Slaanesh Wizards within Command range +1 Casting; enemy Wizards -1 Casting."},
      {n:"Allure of Slaanesh", pts:35, d:"Enemies must pass Ld test before rolling To Hit in Combat; if failed, only 6s hit."},
      {n:"Siren Song", pts:30, d:"Single use. One enemy unit that can charge bearer must pass Ld test or is forced to charge."},
      {n:"Soporific Musk", pts:30, d:"Enemies in combat cannot use Strike First; others gain Strike Last. Extremely Common."},
      {n:"Enrapturing Gaze", pts:20, d:"Enemies in combat cannot use Inspiring Presence. Extremely Common."},
    ],
    "daemons-of-chaos-tzeentch": [
      {n:"Staff of Change", pts:65, d:"S, AP-1. On wound: enemy passes Toughness test or loses all remaining Wounds."},
      {n:"Will of Tzeentch", pts:55, d:"Once per round: re-roll any single D6."},
      {n:"Power Vortex", pts:35, d:"Enemy Wizards within Dispel range suffer -1 to Casting rolls."},
      {n:"Iridescent Corona", pts:30, d:"Enemies targeting bearer in Shooting phase suffer -1 To Hit. Extremely Common."},
      {n:"Twin Heads", pts:20, d:"Bearer knows 1 more spell than normal for their Level."},
    ],
    "beastmen-brayherds-mutations": [
      {n:"Slug-skin", pts:50, d:"Enemies attacking bearer or unit in Combat suffer -1 To Hit."},
      {n:"Crown of Horns", pts:45, d:"Bearer and unit gain Stubborn."},
      {n:"Muscular Monstrosity", pts:35, d:"+1 Strength (not mount)."},
      {n:"Pelt of Midnight", pts:35, d:"Enemies targeting bearer or unit in Shooting suffer -1 To Hit."},
      {n:"Gouge-tusks", pts:30, d:"+1 AP on all weapons in Combat (not mount)."},
      {n:"Rune of the Beast Ascendant", pts:25, d:"Beastman Chieftains only. Friendly Bestigors, Gors, Ungors within Command range gain +1 Ld (max 10)."},
      {n:"Many-limbed Fiend", pts:20, d:"+1 Attack with ordinary hand weapon (not mount)."},
      {n:"Gnarled Hide", pts:15, d:"Infantry only. Gains Armoured Hide (1)."},
      {n:"Uncanny Senses", pts:10, d:"+1 Initiative (not mount)."},
    ],
    "warriors-of-chaos-traits": [
      {n:"Dark Hearts", pts:0, d:"Chars +20pts/model, Units +1pt/model. Infantry/cavalry only. Winning side with majority of Dark Hearts: losing units suffer -1 Ld on Break test."},
      {n:"Unnatural Fortitude", pts:0, d:"Chars +20pts, Units +2pts. Without heavy or full plate: +1 Toughness (max 10)."},
      {n:"Longstriders", pts:0, d:"Chars +15pts, Units +1pt. 0-1 per 1000pts. Without heavy or full plate: gain Vanguard."},
      {n:"Battle Hunger", pts:0, d:"Chars +10pts, Units +20pts. Infantry only. Unit gains +2\" charge range and +D3 on Charge/Pursuit rolls."},
      {n:"Brazen Will", pts:0, d:"Chars +10pts, Units +15pts. Infantry/cavalry only. Unit gains Magic Resistance (-1)."},
      {n:"Enhanced Reflexes", pts:0, d:"Chars +10pts, Units +1pt. +2 Initiative when fighting with a hand weapon in Combat."},
      {n:"Prophetic Foresight", pts:0, d:"Chars +10pts, Units +10pts. Enemies deploying via Scouts cannot be within 18\" (vs 12\"). Ambushers cannot be within 12\" (vs 8\")."},
    ],
    "lizardmen-disciplines": [
      {n:"Higher State of Mind", pts:60, d:"Slann only. Slann can re-roll any single dice per Magic phase."},
      {n:"Becalming Cogitation", pts:50, d:"Slann only. Once per game: automatically dispel one spell with no Dispel roll."},
      {n:"Wandering Deliberations", pts:40, d:"Slann only. Once per Magic phase: know any one spell from any lore as if it were the Slann's lore."},
      {n:"Transcendent Healing", pts:35, d:"Slann only. Once per game: Slann recovers D3 Wounds."},
      {n:"Sorcerous Void", pts:30, d:"Slann only. Once per game: remove all Power and Dispel dice from both pools."},
      {n:"Harrowing Scrutiny", pts:20, d:"Slann only. Enemy Wizards within Dispel range must re-roll Casting rolls of a natural double 1 through 3."},
      {n:"Soul of Stone", pts:10, d:"Slann only. Slann does not scatter when casting a Magical Vortex."},
    ],
    "ogre-kingdoms-bignames": [
      {n:"Mawseeker", pts:30, d:"Bearer has the Scent of Blood rule and gains +D3 Attacks when fighting monsters."},
      {n:"Mountaineater", pts:25, d:"Bearer can re-roll failed rolls To Wound against monsters and giants."},
      {n:"Giantbreaker", pts:20, d:"Bearer has the Armour Bane (D3) special rule when fighting monsters."},
      {n:"Kineater", pts:15, d:"Bearer gains +1 Weapon Skill and +1 Attacks when fighting Ogres."},
      {n:"Longstrider", pts:10, d:"Bearer gains the Vanguard special rule."},
      {n:"Beastkiller", pts:5, d:"Bearer gains Killing Blow when fighting Monsters."},
      {n:"Deathcheater", pts:5, d:"Bearer gains a 6+ Ward save."},
    ],
    "vampire-counts-powers": [
      {n:"Curse of the Revenant", pts:50, d:"Vampire only. Bearer has +1 to their Regeneration save (or gains Regen (6+) if they do not already have it)."},
      {n:"Beguile", pts:40, d:"Vampire only. Enemy models engaged in combat with bearer must re-roll successful To Hit rolls of a natural 6."},
      {n:"Flying Horror", pts:35, d:"Vampire only. Bearer gains the Fly (10) special rule."},
      {n:"Dark Acolyte", pts:30, d:"Vampire Wizards only. +D3 to Invocation of Nehek rolls."},
      {n:"Master of the Black Arts", pts:30, d:"Vampire Wizards only. +1 Power dice per Magic phase."},
      {n:"Supernatural Horror", pts:20, d:"Vampire only. Bearer and unit gain the Terror special rule."},
      {n:"Lord of the Night", pts:15, d:"Vampire only. Bearer and all friendly Undead within 12\" have the Immune to Psychology special rule."},
    ],
    "wood-elf-realms-spites": [
      {n:"Blight of Terrors", pts:50, d:"Enemies within 12\" suffer -2 Ld when making Fear or Terror tests."},
      {n:"Muster of Malevolents", pts:40, d:"Once per game: immediately after an enemy unit passes a Panic test within 12\", they must re-roll it."},
      {n:"Befuddlement of Mischiefs", pts:30, d:"Enemy units within 6\" suffer -1 to their Weapon Skill."},
      {n:"Murder of Spites", pts:25, d:"Bearer has +D3 Attacks. These attacks are at S2, AP-, and Poisoned Attacks."},
      {n:"Lamentation of Despairs", pts:20, d:"Enemies within 6\" suffer -1 to their Initiative."},
      {n:"Annoyance of Netlings", pts:15, d:"Enemy models in base contact with bearer must re-roll To Hit rolls of 6."},
      {n:"Resplendence of Luminescents", pts:10, d:"Bearer has the Ethereal special rule."},
    ],
    "empire-of-man-orders": [
      {n:"Order of the Knights Panther", pts:0, d:"+10pts/character, +2pts/model. Hatred (Chaos). Character has Inspiring Presence (+6\")."},
      {n:"Order of the White Wolf", pts:0, d:"+15pts/character, +3pts/model. Great weapon as additional hand weapon. Immune to Psychology."},
      {n:"Order of the Blazing Sun", pts:0, d:"+10pts/character, +2pts/model. Flaming Attacks. Character can cast Flaming Sword of Rhuin as Bound Spell PL2."},
      {n:"Order of the Knights of Morr", pts:0, d:"+15pts/character, +3pts/model. Hatred (Undead). Character has a 5+ Ward save vs Undead attacks."},
      {n:"Order of the Fiery Heart", pts:0, d:"+15pts/character, +3pts/model. Hatred (Chaos Dwarfs). Once per game, re-roll all To Wound rolls in one combat."},
    ],
    "high-elf-realms-honours": [
      {n:"Loremaster", pts:35, d:"Wizard only. Bearer knows all spells from their chosen lore (including signature)."},
      {n:"Shadow Stalker", pts:20, d:"Bearer and unit gain the Scouts and Vanguard special rules."},
      {n:"Anointed of Asuryan", pts:15, d:"Bearer is immune to Killing Blow. If struck, they may make normal saves."},
      {n:"Blood of Caledor", pts:15, d:"Bearer has the Immune to Psychology special rule and a 4+ Ward save vs Flaming Attacks."},
      {n:"Chracian Hunter", pts:10, d:"Bearer has the Move Through Cover and Hatred (Chaos) special rules."},
      {n:"Warden of Saphery", pts:10, d:"Wizard only. +1 to all Dispel rolls."},
      {n:"Pure of Heart", pts:0, d:"Bearer has the Hatred (Chaos) and Hatred (Dark Elves) special rules."},
      {n:"Sea Guard", pts:0, d:"Bearer has the Swiftstride special rule when on foot."},
    ],
    "kingdom-of-bretonnia-virtues": [
      {n:"Knightly Temper", pts:70, d:"Bearer has the Hatred (all enemies) and Frenzy special rules. Cannot lose Frenzy."},
      {n:"Heroism", pts:60, d:"Bearer has the Terror special rule and a 4+ Ward save."},
      {n:"Stoicism", pts:55, d:"Bearer and unit have the Stubborn special rule and are Immune to Psychology."},
      {n:"Penitent", pts:50, d:"Bearer has +D3 Attacks. Each wound the bearer suffers grants them +1 additional Attack."},
      {n:"Ideal", pts:45, d:"Bearer re-rolls failed rolls To Hit in Combat. Enemies re-roll successful rolls To Hit against bearer."},
      {n:"Impetuous Knight", pts:40, d:"Bearer has the Hatred (all enemies) and Impetuous special rules."},
      {n:"Audacity", pts:35, d:"Bearer has the Strike First special rule. Bearer and unit gain +1 Attacks on the charge."},
      {n:"Purity", pts:30, d:"Bearer has the Magic Resistance (-3) special rule."},
      {n:"Duty", pts:25, d:"Bearer gains +1 Leadership and the Inspiring Presence special rule with +6\" range."},
      {n:"Joust", pts:20, d:"Bearer has the Armour Bane (D3) special rule on the charge."},
      {n:"Confidence", pts:15, d:"Bearer has the Immune to Psychology special rule."},
      {n:"Noble Disdain", pts:10, d:"Bearer and unit gain Hatred (any enemy unit with Skirmishers or Scouts)."},
      {n:"Discipline", pts:5, d:"Bearer and unit may re-roll failed Panic tests."},
      {n:"Empathy", pts:5, d:"Bearer has the Inspiring Presence special rule with +6\" range."},
    ],
    "dwarfs-tattoos": [
      {n:"Rune of the Dishonoured", pts:50, d:"Bearer has +2 Strength and Hatred (all enemies)."},
      {n:"Rune of Endless Battle", pts:40, d:"Bearer has the Heroic Killing Blow and Frenzy special rules."},
      {n:"Rune of the Reckless", pts:35, d:"Bearer has +D3 Attacks determined at the start of each combat."},
      {n:"Rune of the Hateful", pts:30, d:"Bearer has +1 Strength and Hatred (all enemies)."},
      {n:"Rune of Grit", pts:25, d:"Bearer has the Stubborn special rule."},
      {n:"Rune of the Dauntless", pts:15, d:"Bearer has the Immune to Psychology special rule."},
      {n:"Rune of Wrath", pts:15, d:"+1 Strength and +1 Attacks on the charge."},
      {n:"Warrior's Rune", pts:10, d:"+1 Weapon Skill and +1 Initiative."},
      {n:"Rune of Blazing Fury", pts:5, d:"Bearer has the Flaming Attacks special rule."},
    ],
  },
};
