// Rule name translations (FR) — synced from TOW en 1 (RULE_FR). slug → nom français.
window.RULE_FR = {
  "abyssal-howl":`Hurlement Abyssal`,
  "ambushers":`Embusqueurs`,
  "armour-bane":`Arme Perforante`,
  "armoured-hide":`Peau Blindée`,
  "arrows-of-isha":`Flèches d’Isha`,
  "aura-of-the-fay":`Aura Féérique`,
  "balefire-brazier":`Brasero Infernal`,
  "banner-of-the-count":`Bannière du Comte`,
  "banner-of-the-king":`Bannière du Roi`,
  "beast-handlers":`Maître des Bêtes`,
  "bestial-charge":`Charge Bestiale`,
  "blessings-of-the-lady":`Bénédiction de la Dame`,
  "blessings-of-the-volcano-god":`Bénédictions du Dieu Volcan`,
  "blood-rage":`Rage Sanguinaire`,
  "bound-spirits":`Esprits Liés`,
  "brayhorn":`Braillecorne`,
  "butchers-cauldron":`Chaudron de Boucher`,
  "chariot-runners":`Escorteurs de Chars`,
  "choppas":`Kikoup’`,
  "cleaving-blow":`Coup de Fendoir`,
  "close-order":`Ordre Serré`,
  "counter-charge":`Contre-charge`,
  "courage-beyond-compare":`Incomparable Courage`,
  "da-boyz":`Lé Boyz`,
  "daemon-of-khorne":`Démon de Khorne`,
  "daemon-of-nurgle":`Démon de Nurgle`,
  "daemon-of-slaanesh":`Démon de Slaanesh`,
  "daemon-of-tzeentch":`Démon de Tzeentch`,
  "daemonic":`Démoniaque`,
  "defensive-stance":`Posture Défensive`,
  "detachment":`Détachement`,
  "drilled":`Bien Entraînés`,
  "dry-as-dust":`Desséchés`,
  "elven-reflexes":`Réflexes Elfiques`,
  "engine-of-the-gods":`Machine des Dieux`,
  "ensorcelled-weapons":`Armes Ensorcelées`,
  "eternal-hatred":`Haine Éternelle`,
  "eternal-taskmaster":`Éternel Contremaître`,
  "ethereal":`Éthéré`,
  "evasive":`Esquiveur`,
  "expeditionary-marksmen":`Tireurs d’Élite Expéditionnaires`,
  "fast-cavalry":`Cavalerie Rapide`,
  "fear":`Peur`,
  "feigned-flight":`Fuite Feinte`,
  "fight-in-extra-rank":`Combat Sur Plusieurs Rangs`,
  "fire-and-flee":`Tir & Fuite`,
  "first-charge":`Première Charge`,
  "flaming-attacks":`Attaques Enflammées`,
  "flammable":`Inflammable`,
  "fly":`Vol`,
  "forbidden-poisons":`Poisons Interdits`,
  "frenzy":`Frénésie`,
  "furious-charge":`Charge Dévastatrice`,
  "gaze-of-the-gods":`Regard des Dieux`,
  "gifts-of-khaine":`Dons de Khaine`,
  "goad-beast":`Dompteur`,
  "grail-monk":`Moine du Graal`,
  "grail-reliquae":`Reliquaire du Graal`,
  "grand-strategist":`Stratège`,
  "guardian-of-the-sacred-sites":`Gardien des Sites Sacrés`,
  "hatred":`Haine`,
  "hawk-eyed-archer":`Archer à l’Œil de Faucon`,
  "hellbound":`Possédé`,
  "horn-of-isha":`Cor d’Isha`,
  "ignore-panic":`Ignore la Panique`,
  "ignores-cover":`Ignore les Couverts`,
  "immune-to-psychology":`Immunisé à la Psychologie`,
  "impact-hits":`Touches d’Impact`,
  "impetuous":`Impétueux`,
  "implacable-defence":`Défense Implacable`,
  "infernal-favour":`Faveur Infernale`,
  "invocation-of-nehek":`Invocation de Nehek`,
  "killing-blow":`Coup Fatal`,
  "large-target":`Grande Cible`,
  "largely-insignificant":`Complètement Insignifiant`,
  "levies":`Conscrits`,
  "living-saints":`Saints Vivants`,
  "loner":`Solitaire`,
  "look-out-gnoblar":`Gnoblar Longue-vue`,
  "magic-resistance":`Résistance à la Magie`,
  "mark-of-chaos-undivided":`Marque du Chaos Universel`,
  "mark-of-khorne":`Marque de Khorne`,
  "mark-of-nurgle":`Marque de Nurgle`,
  "mark-of-slaanesh":`Marque de Slaanesh`,
  "mark-of-tzeentch":`Marque de Tzeentch`,
  "martial-prowess":`Prouesses Martiales`,
  "mercenaries":`Mercenaires`,
  "mob-rule":`La Loi du Nombre`,
  "monster-handlers":`Dresseurs de Monstres`,
  "motley-crew":`Bande Hétéroclite`,
  "mournfang-charge":`Charge Férox`,
  "move-through-cover":`Mouvement à Couvert`,
  "my-will-be-done":`Que Ma Volonté Soit Faite`,
  "necromantic-undead":`Mort-vivant Nécromantique`,
  "nehekharan-phalanx":`Phalange de Nehekhara`,
  "nehekharan-undead":`Morts-vivants de Nehekhara`,
  "open-order":`Ordre Dispersé`,
  "parry-wood-elves":`Parade`,
  "pavise":`Pavois`,
  "peasants-duty":`Devoir du Paysan`,
  "poisoned-attacks":`Attaques Empoisonnées`,
  "prayers-of-ulric":`Prières d’Ulric`,
  "primal-fury":`Fureur Primale`,
  "quell-impetuosity":`Calme l’Impétuosité`,
  "quell-panic":`Calme la Panique`,
  "rallying-cry":`Cri de Ralliement`,
  "random-movement":`Mouvement Aléatoire`,
  "ravenous-hunger":`Faim Dévorante`,
  "regeneration":`Régénération`,
  "regimental-unit":`Unité Régimentaire`,
  "reserve-move":`Mouvement de Réserve`,
  "resolute":`Résolu`,
  "safe-from-harm":`À l’Abri du Danger`,
  "scouts":`Éclaireurs`,
  "sea-dragon-cloak":`Cape en peau de Dragon des Mers`,
  "shieldwall":`Mur de Boucliers`,
  "skirmish-screen":`Écran de Tirailleurs`,
  "skirmishers":`Tirailleurs`,
  "stampede":`Ruée`,
  "stomp-attacks":`Attaques de Piétinement`,
  "storm-call":`Appeler la Tempête`,
  "strike-first":`Frappe En Premier`,
  "stubborn":`Obstiné`,
  "stupidity":`Stupidité`,
  "suffer-not":`Ne Tolérez Pas...`,
  "swiftstride":`Rapide`,
  "sworn-protector":`Protecteur Assermenté`,
  "talismanic-tattoos":`Tatouages Talismaniques`,
  "terror":`Terreur`,
  "the-exiles-vow":`Le Vœu de l’Exilé`,
  "the-grail-vow":`Le Vœu du Graal`,
  "the-knights-vow":`Le Vœu du Chevalier`,
  "the-questing-vow":`le Vœu de la Quête`,
  "the-wyrm-slayer":`Le Sauroctone`,
  "traps-and-snares":`Pièges & Collets`,
  "troubadour-of-loec":`Troubadour de Loec`,
  "two-heads":`Bicéphale`,
  "unbreakable":`Indémoralisable`,
  "unstable":`Instables`,
  "untutored-arcanist":`Arcaniste Autodidacte`,
  "valour-of-ages":`Valeur des Âges`,
  "vanguard":`Avant-garde`,
  "veteran":`Vétérans`,
  "warband":`Bande de Guerre`,
  "warpaint":`Peintures de Guerre`,
  "warped-tintinnabulation":`Tintinnabulation Dissonante`,
  "warpstone-weapons":`Armes à base de Malepierre`,
  "wight-banner":`Bannière du Revenant`,
  "subterranean-ambush":`Embuscade Souterraine`,
  "ancient-enemies":`Ennemis Ancestraux`,
  "the-awakened-wood":`Le Bois Éveillé`,
  "chieftains-of-the-hunter-king":`Chefs du Roi Chasseur`,
  "daughters-of-eternity":`Filles de l'Éternité`,
  "deepwood-coven":`Cercle des Bois Profonds`,
  "guardians-of-the-wildwood":`Gardiens de la Forêt Sauvage`,
  "in-tune-with-nature":`En Harmonie avec la Nature`,
  "protectors-of-the-ancient-wood":`Protecteurs du Bois Ancestral`,
  "spectral-hounds":`Limiers Spectraux`,
  "the-spirit-of-kurnous":`L'Esprit de Kurnous`,
  "tree-whack":`Coup de Branche`,
  "woodland-ambush":`Embuscade Sylvestre`,
  "worthy-of-kurnous":`Digne de Kurnous`,
  "spirit-of-galrauch":`Esprit de Galrauch`,
  "hellcannon-misfire-table":`Table d'Incident du Canon Infernal`,
  "steeds-of-darkness":`Destriers des Ténèbres`,
  "warped-form":`Forme Difforme`,
  "warpfire-aura":`Aura de Malefeu`,
  "favour-of-the-gods":`Faveur des Dieux`,
  "cursed-by-the-gods":`Maudit par les Dieux`,
  "praising-the-gods":`Louange aux Dieux`,
  "relentless-warriors":`Guerriers Implacables`,
  "forsaken-by-khorne":`Renié par Khorne`,
  "forsaken-by-nurgle":`Renié par Nurgle`,
  "forsaken-by-slaanesh":`Renié par Slaanesh`,
  "forsaken-by-tzeentch":`Renié par Tzeentch`,
  "gigantic-spawn-of-khorne":`Engeance Géante de Khorne`,
  "gigantic-spawn-of-nurgle":`Engeance Géante de Nurgle`,
  "gigantic-spawn-of-slaanesh":`Engeance Géante de Slaanesh`,
  "gigantic-spawn-of-tzeentch":`Engeance Géante de Tzeentch`,
  "spawn-of-khorne":`Engeance de Khorne`,
  "spawn-of-nurgle":`Engeance de Nurgle`,
  "spawn-of-slaanesh":`Engeance de Slaanesh`,
  "spawn-of-tzeentch":`Engeance de Tzeentch`,
  "chaotic-cults":`Cultes Chaotiques`,
  "cult-of-the-bloodied-hound":`Culte du Limier Ensanglanté`,
  "cult-of-the-carrion-crow":`Culte de la Corneille Charognarde`,
  "cult-of-the-fell-raptor":`Culte du Rapace Funeste`,
  "cult-of-the-slithering-serpent":`Culte du Serpent Rampant`,
  "mounted-host":`Horde Montée`,
  "sea-born-raiders":`Pillards venus de la Mer`,
  "explosive-demise":`Trépas Explosif`,
  "fire-and-chaos":`Feu & Chaos`,
  "the-shadow-grows":`L'Ombre Grandit`,
  "warriors-duel":`Duel de Guerriers`,
  "breath-of-change":`Souffle du Changement`,
  "caged-fury":`Fureur Enchaînée`,
  "chaos-armour-warriors-of-chaos":`Armure du Chaos (Guerriers du Chaos)`,
  "chaos-armour-daemons-of-chaos":`Armure du Chaos (Démons du Chaos)`,
  "accursed-weapons":`Armes Maudites`,
  "bestial-fury":`Fureur Bestiale`,
  "the-death-of-a-general":`La Mort d'un Général`,
  "martial-pride":`Fierté Martiale`,
  "spectral-coach":`Carrosse Spectral`,
  "spectral-reapers":`Faucheurs Spectraux`,
  "the-hunger":`La Soif`,
  "attention-seeker":`En Quête d'Attention`,
  "authority-of-the-hierophant":`Autorité du Hiérophante`,
  "commander-of-legions":`Commandeur des Légions`,
  "grind-them-down":`« Écrasez-les ! »`,
  "harmonious-incantations":`Incantations Harmonieuses`,
  "herald-of-despair":`Héraut du Désespoir`,
  "the-hierophant":`Le Hiérophante`,
  "the-language-of-the-priests":`Le Langage des Prêtres`,
  "lay-in-wait":`À l'Affût`,
  "masterful-outriders":`Cavaliers Émérites`,
  "resurrecting-the-fallen":`Ressusciter les Morts`,
  "scarab-prince":`Prince Scarabée`,
  "screaming-skulls":`Crânes Hurlants`,
  "sepulchral-animus":`Animus Sépulcral`,
  "settra-does-not-kneel":`Settra ne s'Agenouille Pas !`,
  "settra-the-great":`Settra le Grand`,
  "settras-champion":`Champion de Settra`,
  "skulls-of-the-foe":`Crânes de l'Ennemi`,
  "soul-reaper":`Faucheur d'Âmes`,
  "steadfast-discipline":`Discipline Inébranlable`,
  "stone-shaper":`Sculpteur de Pierre`,
  "the-terrors-below":`Les Terreurs d'En Bas`,
  "usirians-reaper":`Faux d'Usirian`,
  "khopesh":`Khopesh`,
  "abominable-attacks":`Attaques Abominables`,
  "avalanche-of-flesh":`Avalanche de Chair`,
  "crushing-bulk":`Masse Écrasante`,
  "deploying-weapon-teams":`Déploiement des Équipes d'Armes`,
  "eshin-infiltration":`Infiltration d'Eshin`,
  "feed":`Dévorer`,
  "hidden-skaven":`Caché (Skavens)`,
  "leader-of-the-pack-skaven":`Meneur de Meute (Skavens)`,
  "lightning-strike":`Frappe Foudroyante`,
  "poisoned-wind":`Vent Empoisonné`,
  "targeting-weapon-teams":`Ciblage des Équipes d'Armes`,
  "too-horrible-to-die":`Trop Horrible pour Mourir`,
  "weapon-team-leadership":`Commandement des Équipes d'Armes`,
  "zzzzap":`Zzzzap !`,
  "big-stabbas":`Grandes Piques`,
  "big-uns":`Costauds`,
  "bully":`Brute`,
  "cunning-hunters":`Chasseurs Rusés`,
  "da-troll-calla":`L'Appel à Trolls`,
  "enhanced-regeneration":`Régénération Accrue`,
  "hit-em-fast-and-hit-em-ard":`Frappez Vite et Frappez Fort !`,
  "hunting-packs":`Meutes de Chasse`,
  "indiscriminate-hunger":`Faim Aveugle`,
  "bonegrinder-giant-attacks":`Attaques de Géant Broyeur d'Os`,
  "crush-underfoot":`Écraser sous le Pied`,
  "eadbutt-bonegrinder-giant":`Coup de Boule (Géant Broyeur d'Os)`,
  "grind-its-bones":`Broyer ses Os`,
  "ker-splat":`Splatch`,
  "mighty-swing-bonegrinder-giant":`Coup Puissant (Géant Broyeur d'Os)`,
  "motherly-love":`Amour Maternel`,
  "netters":`Lanceurs de Filets`,
  "oi-dis-way":`Oh ! Par Ici !`,
  "on-da-move":`En Vadrouille`,
  "protect-da-boss":`Protégez le Boss`,
  "skulking-menace":`Menace Tapie`,
  "slimy-shanks":`Pattes Visqueuses`,
  "solitary-fighters":`Combattants Solitaires`,
  "spiked-ball-and-chains":`Boulets à Chaîne Cloutés`,
  "squigs-go-wild":`Squigs Déchaînés`,
  "syphoned-strength":`Force Siphonnée`,
  "troll-tongue":`Langue de Troll`,
  "wallop":`Torgnole`,
  "bellowers-and-musicians":`Beuglards & Musiciens`,
  "running-with-the-pack":`Courir avec la Meute`,
  "waaagh":`Waaagh !`,
  "primeval-roar":`Rugissement Primordial`,
  "guardians":`Gardiens`,
  "arcane-configuration":`Configuration Arcanique`,
  "burning-alignment":`Alignement Ardent`,
  "solar-engine":`Moteur Solaire`,
  "solar-radiance":`Radiance Solaire`,
  "beam-of-chotec":`Rayon de Chotec`,
  "ark-of-sotek":`Arche de Sotek`,
  "slithering-serpents":`Serpents Rampants`,
  "spawn-of-sotek":`Engeance de Sotek`,
  "cold-blooded":`Sang-froid`,
  "impervious-defence":`Défense Impénétrable`,
  "the-crusaders-vow":`Vœu du Croisé`,
  "forming-the-lance":`Former la Lance`,
  "manoeuvring-a-lance":`Manœuvrer une Lance`,
  "the-lance-in-combat":`La Lance au Combat`,
  "blunting-the-lance":`Émousser la Lance`,
  "casualty-removal":`Retrait des Pertes`,
  "characters-joining-a-lance":`Personnages Rejoignant une Lance`,
  "lance-formations-and-skirmishers":`Formations en Lance & Tirailleurs`,
  "crusaders-zeal":`Ferveur du Croisé`,
  "earn-your-spurs":`Gagner ses Éperons`,
  "retinue-of-the-saints":`Suite des Saints`,
  "reclaimed-glory":`Gloire Reconquise`,
  "crusading-knights":`Chevaliers Croisés`,
  "banished-lords":`Seigneurs Bannis`,
  "dragon-armour":`Armure de Dragon`,
  "enfeebling-cold":`Froid Affaiblissant`,
  "abyssal-cloak":`Cape Abyssale`,
  "mighty-constitution":`Constitution Robuste`,
  "precision-strikes":`Frappes de Précision`,
  "commanding-voice":`Voix de Commandement`,
  "kings-guard":`Garde du Roi`,
  "sons-of-caledor":`Fils de Caledor`,
  "chracian-warriors":`Guerriers Chraciens`,
  "warriors-of-nagarythe":`Guerriers de Nagarythe`,
  "warriors-of-the-white-tower":`Guerriers de la Tour Blanche`,
  "warriors-of-chrace":`Guerriers de Chrace`,
  "chracian-pride":`Fierté Chracienne`,
  "hidden-trails":`Sentiers Cachés`,
  "warriors-of-the-wilderness":`Guerriers des Étendues Sauvages`,
  "armies-of-the-sea-lord":`Armées du Seigneur des Mers`,
  "from-the-mists":`Surgis des Brumes`,
  "from-the-storm-clouds":`Surgis des Nuées d'Orage`,
  "old-world-rangers":`Rôdeurs du Vieux Monde`,
  "pride-of-the-fleet":`Fierté de la Flotte`,
  "battle-magic":`Magie de Bataille`,
  "high-magic":`Haute Magie`,
  "unity-and-harmony":`Unité & Harmonie`,
  "implacable":`Implacable`,
  "the-elemental-winds":`Les Vents Élémentaires`,
  "dragon-form":`Forme de Dragon`,
  "human-form":`Forme Humaine`,
  "transformation":`Transformation`,
  "transformation-of-the-dragon":`Transformation du Dragon`,
  "death-of-a-dragon":`Mort d'un Dragon`,
  "disdain-of-the-dragons":`Dédain des Dragons`,
  "discipline-of-the-dragon":`Discipline du Dragon`,
  "cathayan-black-powder":`Poudre Noire Cathayenne`,
  "granite-sentinel":`Sentinelle de Granit`,
  "jade-sentinel":`Sentinelle de Jade`,
  "obsidian-sentinel":`Sentinelle d'Obsidienne`,
  "terracotta-sentinel":`Sentinelle de Terre Cuite`,
  "warpstone-sentinel":`Sentinelle de Malepierre`,
  "wrath-of-the-storm":`Courroux de la Tempête`,
  "enough-for-everyone":`Assez pour Tous`,
  "mastery-of-the-storm-winds":`Maîtrise des Vents de Tempête`,
  "mercenary-crew":`Équipage Mercenaire`,
  "mercenary-handgun-drill":`Manœuvre d'Arquebuse Mercenaire`,
  "supreme-matriarch-of-nan-gau":`Matriarche Suprême de Nan-Gau`,
  "wailing-spirits":`Esprits Gémissants`,
  "war-balloons":`Ballons de Guerre`,
  "warriors-of-the-field":`Guerriers des Champs`,
  "warriors-of-the-land":`Guerriers de la Terre`,
  "warriors-of-the-wind":`Guerriers du Vent`,
  "thunderous-impact":`Impact Tonitruant`,
  "tower-shields":`Pavois`,
  "ancestral-fury":`Fureur Ancestrale`,
  "stoic-defenders":`Défenseurs Stoïques`,
  "striking-a-grudge":`Régler un Grief`,
  "grudgelore":`Savoir des Griefs`,
  "the-grudgestone":`La Pierre des Griefs`,
  "venerable":`Vénérable`,
  "wards-of-grimnir":`Protections de Grimnir`,
  "troll-hunters":`Chasseurs de Trolls`,
  "king-of-the-slayer-hold":`Roi du Fort des Tueurs`,
  "royal-guard":`Garde Royale`,
  "first-to-the-fray":`Premiers dans la Mêlée`,
  "fight-me":`« Affronte-moi ! »`,
  "whirlwind-of-death":`Tourbillon de Mort`,
  "whirling-doom":`Tourbillon Fatal`,
  "from-the-wilds":`Venus des Étendues Sauvages`,
  "prepared-positions":`Positions Préparées`,
  "range-finding-optics":`Optiques de Visée`,
  "function-over-form":`La Fonction avant la Forme`,
  "worst-among-equals":`Le Pire parmi ses Pairs`,
  "riches-and-heirlooms":`Richesses & Héritages`,
  "dive-bomb":`Bombardement en Piqué`,
  "bugmans-cart":`Chariot de Bugman`,
  "miners-cart":`Chariot de Mineurs`,
  "look-snorri-trolls":`« Regarde Snorri, des Trolls ! »`,
  "gromril-armour":`Armure en Gromril`,
  "gromril-weapons":`Armes en Gromril`,
  "ancestral-shield":`Bouclier Ancestral`,
  "deathblow":`Coup Mortel`,
  "slayer":`Tueur`,
  "slayer-of-daemons":`Tueur de Démons`,
  "slayer-of-dragons":`Tueur de Dragons`,
  "rune-lore":`Savoir des Runes`,
  "runes-of-protection":`Runes de Protection`,
  "runes-of-warding":`Runes de Garde`,
  "immovable-object":`Objet Inamovible`,
  "strike-the-runes":`Frapper les Runes`,
  "bombing-run":`Raid de Bombardement`,
  "forgefire":`Feu de Forge`,
  "cry-of-war":`Cri de Guerre`,
  "dance-of-death":`Danse de Mort`,
  "manbane":`Fléau des Hommes`,
  "dark-venom":`Venin Noir`,
  "hidden-dark-elves":`Caché (Elfes Noirs)`,
  "cursed-coven":`Cercle Maudit`,
  "witchbrew":`Breuvage de Sorcière`,
  "rune-of-khaine":`Rune de Khaine`,
  "black-lotus":`Lotus Noir`,
  "wilful-beast":`Bête Indocile`,
  "dark-runes":`Runes Noires`,
  "murderous":`Meurtrier`,
  "daemonic-alignment":`Alignement Démoniaque`,
  "daemonic-locus":`Locus Démoniaque`,
  "brazen-wheels":`Roues d'Airain`,
  "plague-proboscis":`Trompe Pestilentielle`,
  "slime-trail":`Traînée de Bave`,
  "daemonic-instability":`Instabilité Démoniaque`,
  "daemonic-charge":`Charge Démoniaque`,
  "scintillating-sorcery":`Sorcellerie Scintillante`,
  "soporific-musk":`Musc Soporifique`,
  "gorefeast":`Festin Sanglant`,
  "cannonade":`Canonnade`,
  "carriage-hauler":`Tracteur de Convoi`,
  "lumbering-destruction":`Destruction Pesante`,
  "quake":`Séisme`,
  "skullcracker":`Brise-Crânes`,
  "slow-reload":`Rechargement Lent`,
  "champions-of-slaughter":`Champions du Carnage`,
  "bloodshed-and-butchery":`Effusion de Sang & Boucherie`,
  "spurting-bile-blood":`Sang de Bile Jaillissant`,
  "maddening-aura":`Aura Affolante`,
  "swallow-whole":`Avaler Tout Cru`,
  "eadbutt-giant":`Coup de Boule (Géant)`,
  "belly-flop":`Plat Ventre`,
  "mighty-swing-giant":`Coup Puissant (Géant)`,
  "thump-with-club":`Coup de Gourdin`,
  "jump-up-and-down":`Sauter à Pieds Joints`,
  "endless-malice":`Malveillance Sans Fin`,
  "soul-eater":`Mangeur d'Âmes`,
  "ghostsight":`Vue Spectrale`,
  "the-quickening-storm":`La Tempête Vivifiante`,
  "dark-coven":`Cercle Sombre`,
  "ancient-sorcery":`Sorcellerie Ancienne`,
  "magics-of-the-dark-gods":`Magies des Dieux Sombres`,
  "leering-spirit":`Esprit Sournois`,
  "herdstones":`Pierres des Hardes`,
  "guardians-of-the-herdstones":`Gardiens des Pierres des Hardes`,
  "blessings-of-chaos":`Bénédictions du Chaos`,
  "roaming-warbands":`Bandes Errantes`,
  "the-sons-of-ghorros":`Les Fils de Ghorros`,
  "father-of-beasts":`Père des Bêtes`,
  "future-sight":`Vision du Futur`,
  "gifts-from-the-dark-gods":`Dons des Dieux Sombres`,
  "leader-of-the-pack-beastmen":`Meneur de Meute (Hommes-Bêtes)`,
  "assorted-weapons":`Armes Disparates`,
  "big-guns-know-no-fear":`Les Grosses Pièces n'ont Pas Peur`,
  "entrenched-position":`Position Retranchée`,
  "fanatical-zeal":`Ferveur Fanatique`,
  "feel-no-pain":`Insensible à la Douleur`,
  "grand-master-of-the-knights-panther":`Grand Maître des Chevaliers Panthère`,
  "grinding-wheels":`Roues Broyeuses`,
  "guardians-of-the-temple":`Gardiens du Temple`,
  "gun-limbers":`Avant-trains d'Artillerie`,
  "handgun-drill":`Manœuvre d'Arquebuse`,
  "helblaster":`Helblaster`,
  "helstorm":`Helstorm`,
  "inner-circle":`Cercle Intérieur`,
  "the-knightly-orders":`Les Ordres de Chevalerie`,
  "knights-of-morr":`Chevaliers de Morr`,
  "knights-of-the-blazing-sun":`Chevaliers du Soleil Ardent`,
  "knights-of-the-fiery-heart":`Chevaliers du Cœur Ardent`,
  "knights-of-the-white-wolf":`Chevaliers du Loup Blanc`,
  "knights-panther":`Chevaliers Panthère`,
  "mercenary-commander":`Commandant Mercenaire`,
  "prayer-of-the-damned":`Prière des Damnés`,
  "skilled-duellist":`Duelliste Habile`,
  "steam-power":`Vapeur Motrice`,
  "strategic-mastery":`Maîtrise Stratégique`,
  "temperamental":`Capricieux`,
  "veteran-outriders":`Hussards Vétérans`,
  "zealot":`Zélote`,
  "regimental-leadership":`Commandement Régimentaire`,
  "regimental-psychology":`Psychologie Régimentaire`,
  "supporting-actions":`Actions de Soutien`,
  "breath-weapon":`Arme à Souffle`,
  "cumbersome":`Encombrant`,
  "dragged-along":`Tracté`,
  "extra-attacks":`Attaques Supplémentaires (+X)`,
  "horde":`Horde`,
  "howdah":`Howdah`,
  "magical-attacks":`Attaques Magiques`,
  "monster-slayer":`Tueur de Monstres`,
  "move-and-shoot":`Bouger & Tirer`,
  "move-or-shoot":`Bouger ou Tirer`,
  "multiple-shots":`Tirs Multiples (X)`,
  "multiple-wounds":`Blessures Multiples (X)`,
  "ponderous":`Pesant`,
  "quick-shot":`Tir Rapide`,
  "random-attacks":`Attaques Aléatoires`,
  "requires-two-hands":`Nécessite Deux Mains`,
  "strike-last":`Frappe en Dernier`,
  "timmm-berrr":`Timmm-berrr !`,
  "volley-fire":`Tir en Salve`,
  "warp-spawned":`Né du Warp`,
  "stomp":`Piétinement`,
  "thunder-stomp":`Piétinement Dévastateur`,
  "battle-line":`Ligne de Bataille`,
  "ward-save":`Sauvegarde Invulnérable`,
  "swarm":`Nuées`,
  "mixed-unit":`Unité Mixte`,
  "skirmish-formation":`Formation en Tirailleurs`,
  "open-order-formation":`Formation en Ordre Ouvert`,
  "strength-in-numbers":`La Force du Nombre`,
  "oathstone":`Pierre du Serment`,
  "mastery-of-the-elemental-winds":`Maîtrise des Vents Élémentaires`,
  "celestial-forged-armour":`Armure Forgée des Cieux`,
  "accursed-reliquary":`Reliquaire Maudit`,
  "all-sneaky-like":`En Douce`,
  "arise":`« Relevez-vous ! »`,
  "artillery-master":`Maître Artilleur`,
  "beguiling-aura":`Aura Enjôleuse`,
  "blasphemous-tome":`Grimoire Blasphématoire`,
  "blessings-of-grimnir":`Bénédictions de Grimnir`,
  "blessings-of-khaine":`Bénédictions de Khaine`,
  "blessings-of-the-horned-rat":`Bénédictions du Rat Cornu`,
  "blessings-of-ulric":`Bénédictions d'Ulric`,
  "blizzard-aura":`Aura de Blizzard`,
  "blood-frenzy":`Frénésie Sanguinaire`,
  "boldest-of-the-bold":`Le Plus Hardi des Hardis`,
  "born-of-fire":`Né du Feu`,
  "borne-aloft":`Porté par les Airs`,
  "bull-charge":`Charge de Taureau`,
  "carrion-feeders":`Charognards`,
  "cathayan-cataphracts":`Cataphractes Cathayens`,
  "chainmaker":`Forgeur de Chaînes`,
  "champions-of-chrace":`Champions de Chrace`,
  "cloud-of-dust":`Nuage de Poussière`,
  "cloud-of-flies":`Nuée de Mouches`,
  "clouds-of-soot-and-smoke":`Nuées de Suie & de Fumée`,
  "commander-and-captain":`Commandant & Capitaine`,
  "covenant-of-power":`Pacte de Puissance`,
  "crown-of-antlers":`Couronne de Bois`,
  "crushing-weight":`Poids Écrasant`,
  "dances-of-loec":`Danses de Loec`,
  "deflect-shots":`Dévier les Tirs`,
  "dig-in":`« Retranchez-vous ! »`,
  "disengage":`Désengagement`,
  "dispersed-formation":`Formation Dispersée`,
  "drop-rocks":`Larguer des Rochers`,
  "entrenchment":`Retranchement`,
  "extended-formation":`Formation Étendue`,
  "eye-of-the-dragon":`Œil du Dragon`,
  "favour-of-the-goddess":`Faveur de la Déesse`,
  "from-beneath-the-sands":`Surgis des Sables`,
  "from-the-ashes":`Renaître des Cendres`,
  "ghoulish-glamour":`Charme Goule`,
  "giant-attacks":`Attaques de Géant`,
  "great-censer":`Grand Encensoir`,
  "handler":`Maître-Bête`,
  "heavenly-beacon":`Phare Céleste`,
  "hekartis-blessing":`Bénédiction de Hekarti`,
  "hit-and-run":`Frappe & Fuite`,
  "holy-fervour":`Ferveur Sacrée`,
  "hostile-terrain":`Terrain Hostile`,
  "immortal-overseer":`Surveillant Immortel`,
  "infernal-engineer":`Ingénieur Infernal`,
  "infested":`Infesté`,
  "it-and-run":`Frappe & Fuite`,
  "marks-of-chaos":`Marques du Chaos`,
  "master-of-ballistics":`Maître Balisticien`,
  "numbing-chill":`Froid Engourdissant`,
  "peerless-raider":`Pillard Sans Égal`,
  "pick-up-and":`Attraper et...`,
  "prayers-of-sigmar":`Prières de Sigmar`,
  "rampant-mutation":`Mutation Galopante`,
  "release-the-fanatics":`« Lâchez les Fanatiques ! »`,
  "scrying-pool":`Bassin de Divination`,
  "scurrying-masses":`Masses Grouillantes`,
  "skaryn-the-eye-thief":`Skaryn le Voleur d'Yeux`,
  "slaughterers-call":`Appel du Massacreur`,
  "slavering-charge":`Charge Baveuse`,
  "sorcerers-curse":`Malédiction du Sorcier`,
  "sorcerous-miasma":`Miasme Sorcier`,
  "stable-firing-platform":`Plateforme de Tir Stable`,
  "stand-back-chief":`« Recule, Chef ! »`,
  "stone-skeleton":`Squelette de Pierre`,
  "symbol-of-might":`Symbole de Puissance`,
  "the-arrow-of-kurnous":`La Flèche de Kurnous`,
  "the-newly-dead":`Les Nouveaux Morts`,
  "thunderous-charge":`Charge Tonitruante`,
  "toad-rage":`Rage du Crapaud`,
  "tolling-the-bell":`Sonner la Cloche`,
  "totem-of-endless-bloodletting":`Totem du Carnage Sans Fin`,
  "two-headed-dragon":`Dragon à Deux Têtes`,
  "unbound-spirits":`Esprits Déliés`,
  "unstoppable-assault":`Assaut Irrésistible`,
  "vortex-of-souls":`Vortex d'Âmes`,
  "wake-of-fire":`Sillage de Feu`,
  "witch-bane":`Fléau des Sorcières`,
  "witness-to-destiny":`Témoin du Destin`,
};
